-- =============================================
-- Table: cloud_data_warehouse.admin
-- Columns: 55
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.admin (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_src_sys_nm VARCHAR(80),
    meta_iud_flg VARCHAR(1),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    system_number BIGINT,
    sponsor_number BIGINT,
    schedule_number BIGINT,
    description VARCHAR(50),
    active VARCHAR(1),
    electronic_fee VARCHAR(1),
    discount_admin_fee NUMERIC(18, 4),
    discount_percentage NUMERIC(18, 4),
    switch_1 NUMERIC(18, 4),
    paper_1 NUMERIC(18, 4),
    direct_1 NUMERIC(18, 4),
    dmr_1 NUMERIC(18, 4),
    eps_1 NUMERIC(18, 4),
    mail_1 NUMERIC(18, 4),
    other_1 NUMERIC(18, 4),
    card_1 NUMERIC(18, 4),
    broker_fee_1 NUMERIC(18, 4),
    broker_percentage_1 NUMERIC(18, 4),
    medicaid_subrogation_fee_1 NUMERIC(18, 4),
    switch_2 NUMERIC(18, 4),
    paper_2 NUMERIC(18, 4),
    direct_2 NUMERIC(18, 4),
    dmr_2 NUMERIC(18, 4),
    eps_2 NUMERIC(18, 4),
    mail_2 NUMERIC(18, 4),
    other_2 NUMERIC(18, 4),
    card_2 NUMERIC(18, 4),
    broker_fee_2 NUMERIC(18, 4),
    broker_percentage_2 NUMERIC(18, 4),
    medicaid_subrogation_fee_2 NUMERIC(18, 4),
    switch_3 NUMERIC(18, 4),
    paper_3 NUMERIC(18, 4),
    direct_3 NUMERIC(18, 4),
    dmr_3 NUMERIC(18, 4),
    eps_3 NUMERIC(18, 4),
    mail_3 NUMERIC(18, 4),
    other_3 NUMERIC(18, 4),
    card_3 NUMERIC(18, 4),
    broker_fee_3 NUMERIC(18, 4),
    broker_percentage_3 NUMERIC(18, 4),
    medicaid_subrogation_fee_3 NUMERIC(18, 4),
    add_id VARCHAR(15),
    change_id VARCHAR(15),
    service_fee_1 NUMERIC(18, 4),
    service_fee_2 NUMERIC(18, 4),
    service_fee_3 NUMERIC(18, 4),
    per_member_fee NUMERIC(18, 2),
    per_employee_fee NUMERIC(18, 2)
);
