-- =============================================
-- Table: cloud_data_warehouse.claimscob
-- Columns: 100
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.claimscob (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_src_sys_nm VARCHAR(80),
    meta_iud_flg VARCHAR(1),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    batch VARCHAR(10) NOT NULL,
    claim_number INTEGER NOT NULL,
    other_payer_count INTEGER NOT NULL,
    op_cov_type VARCHAR(5),
    op_id_qual VARCHAR(5),
    op_id VARCHAR(15),
    op_date DATE,
    op_amt_count INTEGER,
    op_amt_qual_1 VARCHAR(5),
    op_amt_paid_1 NUMERIC(18, 2),
    op_amt_qual_2 VARCHAR(5),
    op_amt_paid_2 NUMERIC(18, 2),
    op_amt_qual_3 VARCHAR(5),
    op_amt_paid_3 NUMERIC(18, 2),
    op_amt_qual_4 VARCHAR(5),
    op_amt_paid_4 NUMERIC(18, 2),
    op_amt_qual_5 VARCHAR(5),
    op_amt_paid_5 NUMERIC(18, 2),
    op_amt_qual_6 VARCHAR(5),
    op_amt_paid_6 NUMERIC(18, 2),
    op_amt_qual_7 VARCHAR(5),
    op_amt_paid_7 NUMERIC(18, 2),
    op_amt_qual_8 VARCHAR(5),
    op_amt_paid_8 NUMERIC(18, 2),
    op_amt_qual_9 VARCHAR(5),
    op_amt_paid_9 NUMERIC(18, 2),
    op_reject_count INTEGER,
    op_reject_code_1 VARCHAR(6),
    op_reject_code_2 VARCHAR(6),
    op_reject_code_3 VARCHAR(6),
    op_reject_code_4 VARCHAR(6),
    op_reject_code_5 VARCHAR(6),
    op_pat_resp_amt_count INTEGER,
    op_pat_resp_amt_qual_1 VARCHAR(5),
    op_pat_resp_amt_1 NUMERIC(18, 2),
    op_pat_resp_amt_qual_2 VARCHAR(5),
    op_pat_resp_amt_2 NUMERIC(18, 2),
    op_pat_resp_amt_qual_3 VARCHAR(5),
    op_pat_resp_amt_3 NUMERIC(18, 2),
    op_pat_resp_amt_qual_4 VARCHAR(5),
    op_pat_resp_amt_4 NUMERIC(18, 2),
    op_pat_resp_amt_qual_5 VARCHAR(5),
    op_pat_resp_amt_5 NUMERIC(18, 2),
    op_pat_resp_amt_qual_6 VARCHAR(5),
    op_pat_resp_amt_6 NUMERIC(18, 2),
    op_pat_resp_amt_qual_7 VARCHAR(5),
    op_pat_resp_amt_7 NUMERIC(18, 2),
    op_pat_resp_amt_qual_8 VARCHAR(5),
    op_pat_resp_amt_8 NUMERIC(18, 2),
    op_pat_resp_amt_qual_9 VARCHAR(5),
    op_pat_resp_amt_9 NUMERIC(18, 2),
    op_pat_resp_amt_qual_10 VARCHAR(5),
    op_pat_resp_amt_10 NUMERIC(18, 2),
    op_pat_resp_amt_qual_11 VARCHAR(5),
    op_pat_resp_amt_11 NUMERIC(18, 2),
    op_pat_resp_amt_qual_12 VARCHAR(5),
    op_pat_resp_amt_12 NUMERIC(18, 2),
    op_pat_resp_amt_qual_13 VARCHAR(5),
    op_pat_resp_amt_13 NUMERIC(18, 2),
    op_pat_resp_amt_qual_14 VARCHAR(5),
    op_pat_resp_amt_14 NUMERIC(18, 2),
    op_pat_resp_amt_qual_15 VARCHAR(5),
    op_pat_resp_amt_15 NUMERIC(18, 2),
    op_pat_resp_amt_qual_16 VARCHAR(5),
    op_pat_resp_amt_16 NUMERIC(18, 2),
    op_pat_resp_amt_qual_17 VARCHAR(5),
    op_pat_resp_amt_17 NUMERIC(18, 2),
    op_pat_resp_amt_qual_18 VARCHAR(5),
    op_pat_resp_amt_18 NUMERIC(18, 2),
    op_pat_resp_amt_qual_19 VARCHAR(5),
    op_pat_resp_amt_19 NUMERIC(18, 2),
    op_pat_resp_amt_qual_20 VARCHAR(5),
    op_pat_resp_amt_20 NUMERIC(18, 2),
    op_pat_resp_amt_qual_21 VARCHAR(5),
    op_pat_resp_amt_21 NUMERIC(18, 2),
    op_pat_resp_amt_qual_22 VARCHAR(5),
    op_pat_resp_amt_22 NUMERIC(18, 2),
    op_pat_resp_amt_qual_23 VARCHAR(5),
    op_pat_resp_amt_23 NUMERIC(18, 2),
    op_pat_resp_amt_qual_24 VARCHAR(5),
    op_pat_resp_amt_24 NUMERIC(18, 2),
    op_pat_resp_amt_qual_25 VARCHAR(5),
    op_pat_resp_amt_25 NUMERIC(18, 2),
    ben_stage_count INTEGER,
    ben_stage_qual_1 VARCHAR(5),
    ben_stage_amt_1 NUMERIC(18, 2),
    ben_stage_qual_2 VARCHAR(5),
    ben_stage_amt_2 NUMERIC(18, 2),
    ben_stage_qual_3 VARCHAR(5),
    ben_stage_amt_3 NUMERIC(18, 2),
    ben_stage_qual_4 VARCHAR(5),
    ben_stage_amt_4 NUMERIC(18, 2),
    claim_key VARCHAR(14)
);
