-- =============================================
-- Table: cloud_data_warehouse.claim_accumulation
-- Columns: 89
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.claim_accumulation (
    claim_key VARCHAR(14),
    paid_or_reversal_flag VARCHAR(1),
    claim_batch_number VARCHAR(8),
    claim_number INTEGER,
    claims_counter INTEGER,
    claim_type INTEGER,
    payment_direct INTEGER,
    pharmacy_number VARCHAR(6),
    chain_number INTEGER,
    pharmacy_name VARCHAR(60),
    reject_code_01 INTEGER,
    reject_code_02 INTEGER,
    rx_number BIGINT,
    rx_date BIGINT,
    drug_type_code INTEGER,
    national_drug_code VARCHAR(11),
    product_name VARCHAR(25),
    new_refill_ind VARCHAR(1),
    metric_quantity NUMERIC(18, 3),
    days_supply INTEGER,
    ingredient_cost_billed NUMERIC(18, 2),
    ingredient_cost_paid NUMERIC(18, 2),
    dispensing_fee NUMERIC(18, 2),
    copay NUMERIC(18, 2),
    tax NUMERIC(18, 2),
    total_amount_paid NUMERIC(18, 2),
    ucr_amount NUMERIC(18, 2),
    member_birth_date BIGINT,
    member_sex VARCHAR(1),
    cardholder_number VARCHAR(10),
    member_number VARCHAR(2),
    alternate_card_number VARCHAR(13),
    patient_relationship VARCHAR(1),
    dea_number VARCHAR(50),
    diagnosis_code VARCHAR(6),
    pdm_system_number INTEGER,
    pdm_sponsor_number INTEGER,
    pdm_group_number VARCHAR(20),
    group_number VARCHAR(20),
    generic_code VARCHAR(1),
    mac_number INTEGER,
    daw_ind VARCHAR(1),
    therapeutic_class_code INTEGER,
    rx_otc_code VARCHAR(1),
    gpi VARCHAR(14),
    exception_code_01 INTEGER,
    override_code_01 INTEGER,
    period_ending_date BIGINT,
    paid_date VARCHAR(256),
    compound_code INTEGER,
    batch_date BIGINT,
    claim_counter INTEGER,
    mail_order VARCHAR(1),
    benefit_code VARCHAR(16),
    awp NUMERIC(18, 2),
    claim_ind VARCHAR(1),
    drug_preference_ind VARCHAR(1),
    pricing_ind VARCHAR(1),
    drug_manufacturer VARCHAR(10),
    controlled_substance VARCHAR(5),
    last_name VARCHAR(20),
    first_name VARCHAR(15),
    middle_init VARCHAR(1),
    third_party_code VARCHAR(1),
    pharmacy_npi_number VARCHAR(10),
    d0_rx_number BIGINT,
    other_coverage_code INTEGER,
    deductible_amount NUMERIC(18, 2),
    number_on_card VARCHAR(20),
    filler_1 VARCHAR(3),
    filler_2 VARCHAR(3),
    amountcopay NUMERIC(18, 2),
    amountcoinsurance NUMERIC(18, 2),
    physician_number VARCHAR(14),
    physician_name VARCHAR(100),
    p_date BIGINT,
    reversal_date BIGINT,
    amount_applied_to_oop NUMERIC(18, 2),
    accumulator_applied_ind VARCHAR(10),
    diagnosis_code_icd10 VARCHAR(10),
    amount_coinsurance NUMERIC(18, 2),
    amount_copay NUMERIC(18, 2),
    penalty_amount NUMERIC(18, 2),
    admin_fee_claims NUMERIC(18, 2),
    filler_one VARCHAR(1),
    filler_two VARCHAR(30),
    etl_insert_date DATE,
    uid VARCHAR(256),
    process_date DATE
);
