-- =============================================
-- Table: cloud_data_warehouse.claims
-- Columns: 357
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.claims (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_src_sys_nm VARCHAR(80),
    meta_iud_flg VARCHAR(1),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    claim_key VARCHAR(14) NOT NULL,
    batch_number VARCHAR(8),
    claim_number BIGINT,
    claim_type BIGINT,
    payment_dir BIGINT,
    cardholder_number VARCHAR(10),
    member_number VARCHAR(2),
    pharmacy_number BIGINT,
    network_key VARCHAR(16),
    chain_number BIGINT,
    reject_code_1 BIGINT,
    reject_code_2 BIGINT,
    process_date DATE,
    rx_number BIGINT,
    rx_date DATE,
    rx_time TIMESTAMP,
    new_refill VARCHAR(1),
    generic_code VARCHAR(1),
    drug_pref_ind VARCHAR(2),
    metric_quantity NUMERIC(18, 3),
    days_supply BIGINT,
    ing_billed NUMERIC(18, 2),
    ing_paid NUMERIC(18, 2),
    disp_fee NUMERIC(18, 2),
    copay NUMERIC(18, 2),
    tax NUMERIC(18, 2),
    admin_fee NUMERIC(18, 2),
    amount_paid NUMERIC(18, 2),
    ucr_amount NUMERIC(18, 2),
    awp_processed NUMERIC(18, 5),
    generic_savings NUMERIC(18, 2),
    member_birth DATE,
    sex VARCHAR(1),
    cardholder_key VARCHAR(20),
    physician_key VARCHAR(14),
    diagnosis_code VARCHAR(6),
    group_number BIGINT,
    drug_key VARCHAR(15),
    gpi VARCHAR(14),
    ndc_type_code BIGINT,
    ndc NUMERIC(11, 0),
    main_drug VARCHAR(1),
    benefit_key VARCHAR(24),
    copay_key VARCHAR(12),
    copay_table BIGINT,
    dispense_table BIGINT,
    plan_key VARCHAR(16),
    plan_number VARCHAR(8),
    mac_number BIGINT,
    daw_indicator VARCHAR(1),
    compound_code BIGINT,
    third_party_code VARCHAR(1),
    rx_otc VARCHAR(1),
    adjustment_code_2 BIGINT,
    generic_table BIGINT,
    reimb_rate_table BIGINT,
    mail_order_flag VARCHAR(1),
    line_number BIGINT,
    claims_counter BIGINT,
    current_claim_indicator VARCHAR(1),
    period_ending DATE,
    paid_date DATE,
    price_indicator VARCHAR(1),
    adjustment_code BIGINT,
    network_number BIGINT,
    step_therapy_number BIGINT,
    pcp_number VARCHAR(14),
    date_key VARCHAR(14),
    exception_01 BIGINT,
    override_1 BIGINT,
    rel_code VARCHAR(2),
    skip_limit_flag BIGINT,
    exception_02 BIGINT,
    exception_03 BIGINT,
    exception_04 BIGINT,
    exception_05 BIGINT,
    exception_06 BIGINT,
    exception_07 BIGINT,
    exception_08 BIGINT,
    exception_09 BIGINT,
    exception_10 BIGINT,
    exception_11 BIGINT,
    exception_12 BIGINT,
    exception_13 BIGINT,
    exception_14 BIGINT,
    exception_15 BIGINT,
    exception_16 BIGINT,
    exception_17 BIGINT,
    exception_18 BIGINT,
    exception_19 BIGINT,
    exception_20 BIGINT,
    override_2 BIGINT,
    override_3 BIGINT,
    override_4 BIGINT,
    override_5 BIGINT,
    override_6 BIGINT,
    override_7 BIGINT,
    override_8 BIGINT,
    override_9 BIGINT,
    override_10 BIGINT,
    form_gt BIGINT,
    maint_gt BIGINT,
    physician_key_2 VARCHAR(18),
    adj_code_1 BIGINT,
    adj_code_info BIGINT,
    coverage_type VARCHAR(1),
    orig_rx_date VARCHAR(8),
    refills_auth BIGINT,
    refill_count_num BIGINT,
    reversal_code BIGINT,
    sys_number BIGINT,
    sponsor_number BIGINT,
    upd_code BIGINT,
    pho_number VARCHAR(14),
    claim_cnty VARCHAR(2),
    member_first_name VARCHAR(15),
    member_middle_initial VARCHAR(1),
    member_last_name VARCHAR(20),
    version_number VARCHAR(1),
    awp_100_percent NUMERIC(18, 2),
    diff_ing_paid NUMERIC(18, 2),
    diff_disp_fee NUMERIC(18, 2),
    diff_table_number BIGINT,
    mac_reference_price NUMERIC(18, 2),
    contract_rate_price NUMERIC(18, 2),
    order_number VARCHAR(20),
    dispensing_status VARCHAR(1),
    assoc_rx_date DATE,
    assoc_rx_number BIGINT,
    intended_days_supply BIGINT,
    partial_ing_cost_paid NUMERIC(18, 2),
    intended_met_qty NUMERIC(18, 3),
    ta_amount NUMERIC(18, 2),
    other_coverage_code BIGINT,
    other_payor_amount NUMERIC(18, 2),
    date_of_injury DATE,
    indep_code BIGINT,
    penalty_amount NUMERIC(18, 2),
    patient_last_name VARCHAR(20),
    patient_middle_initial VARCHAR(1),
    patient_first_name VARCHAR(15),
    sub_clarification_code_1 BIGINT,
    sub_clarification_code_2 BIGINT,
    sub_clarification_code_3 BIGINT,
    pa_mc_code_and_number NUMERIC(12, 0),
    level_of_service BIGINT,
    max_amt NUMERIC(18, 2),
    deduct_amt NUMERIC(18, 2),
    dmr_nabp BIGINT,
    other_payer_order BIGINT,
    nonlics_deduct_amt NUMERIC(18, 2),
    standard_deduct_amt NUMERIC(18, 2),
    special_deduct_amt NUMERIC(18, 2),
    team_member VARCHAR(4),
    npi_number VARCHAR(10),
    card_seq_number BIGINT,
    add_to_troop NUMERIC(18, 2),
    pcn VARCHAR(10),
    bin_number BIGINT,
    eft_payment VARCHAR(1),
    medd_gap_discount NUMERIC(18, 2),
    medd_beg_phase VARCHAR(1),
    medd_end_phase VARCHAR(1),
    rxnumber_length BIGINT,
    patient_paid_amount NUMERIC(18, 2),
    sub_clarification_count BIGINT,
    other_payer_bin BIGINT,
    trans_ref_number VARCHAR(10),
    other_payer_pcn VARCHAR(14),
    other_payer_group VARCHAR(14),
    soj VARCHAR(2),
    other_payer_cardholder VARCHAR(20),
    compound_dosage_description_code VARCHAR(2),
    compound_dispensing_id VARCHAR(1),
    compound_count BIGINT,
    amt_applied_period_deduct NUMERIC(18, 2),
    amt_exceed_period_benefit NUMERIC(18, 2),
    amt_copay NUMERIC(18, 2),
    amt_coinsurance NUMERIC(18, 2),
    amt_attr_processor_fee NUMERIC(18, 2),
    amt_attr_sales_tax NUMERIC(18, 2),
    amt_attr_provider_net_select NUMERIC(18, 2),
    amt_attr_prod_sel_brand NUMERIC(18, 2),
    amt_attr_prod_sel_non_pf NUMERIC(18, 2),
    amt_attr_prod_sel_brd_non_pf NUMERIC(18, 2),
    health_plan_funded_assist_amt NUMERIC(18, 2),
    gross_amount_due NUMERIC(18, 2),
    incentive_amount_sub NUMERIC(18, 2),
    dispensing_fee_sub NUMERIC(18, 2),
    other_amount_claimed_sub NUMERIC(18, 2),
    flat_sales_tax_amount_sub NUMERIC(18, 2),
    pct_sales_tax_amount_sub NUMERIC(18, 2),
    pct_sales_tax_rate_sub NUMERIC(18, 4),
    medicaid_subrogation VARCHAR(20),
    medicaid_paid_amt NUMERIC(18, 2),
    pharmacy_service_type BIGINT,
    pharmacist_license VARCHAR(50),
    sequence_number VARCHAR(20),
    uid VARCHAR(36),
    nabp_7 VARCHAR(7),
    preferred_status VARCHAR(1),
    rx_origin_code BIGINT,
    customer_location BIGINT,
    eligibility_clarification_code BIGINT,
    primary_prescriber VARCHAR(10),
    basis_of_cost_determination VARCHAR(2),
    document_number BIGINT,
    processor_control_flag VARCHAR(1),
    dmr_reimbursement_payment_type BIGINT,
    pharmacy_option VARCHAR(1),
    pharmacy_name VARCHAR(30),
    product_description_abbreviation VARCHAR(25),
    alt_cardholder_number VARCHAR(13),
    alt_group_number VARCHAR(12),
    thera_class BIGINT,
    rx_otc_class VARCHAR(1),
    batch_date DATE,
    benefit_code VARCHAR(16),
    claim_indicator VARCHAR(1),
    rx_date_julian BIGINT,
    batch_date_julian BIGINT,
    county VARCHAR(2),
    seq_number VARCHAR(20),
    physician_number_x VARCHAR(50),
    cms_part_d_facility VARCHAR(1),
    approved_msg_code VARCHAR(3),
    time_hhmm VARCHAR(4),
    restack_batch VARCHAR(8),
    restack_claim BIGINT,
    variable_mac_factor_rate NUMERIC(18, 5),
    patient_residency VARCHAR(2),
    special_packaging_ind VARCHAR(1),
    prof_service_code_1 VARCHAR(2),
    prof_service_code_2 VARCHAR(2),
    prof_service_code_3 VARCHAR(2),
    dur_pps_lvl_of_effort VARCHAR(2),
    troop_amt NUMERIC(18, 2),
    redemption_count BIGINT,
    date_of_reversal DATE,
    packaging_indicator VARCHAR(1),
    no_financial_flag VARCHAR(1),
    claim_type_alpha VARCHAR(2),
    ltc_indicator VARCHAR(1),
    dur_lvl_of_effort_1 VARCHAR(2),
    dur_reason_service_1 VARCHAR(2),
    dur_prof_service_code_1 VARCHAR(2),
    dur_result_of_serv_cd_1 VARCHAR(2),
    dur_lvl_of_effort_2 VARCHAR(2),
    dur_reason_service_2 VARCHAR(2),
    dur_prof_service_code_2 VARCHAR(2),
    dur_result_of_serv_cd_2 VARCHAR(2),
    dur_lvl_of_effort_3 VARCHAR(2),
    dur_reason_service_3 VARCHAR(2),
    dur_prof_service_code_3 VARCHAR(2),
    dur_result_of_serv_cd_3 VARCHAR(2),
    dur_lvl_of_effort_4 VARCHAR(2),
    dur_reason_service_4 VARCHAR(2),
    dur_prof_service_code_4 VARCHAR(2),
    dur_result_of_serv_cd_4 VARCHAR(2),
    dur_lvl_of_effort_5 VARCHAR(2),
    dur_reason_service_5 VARCHAR(2),
    dur_prof_service_code_5 VARCHAR(2),
    dur_result_of_serv_cd_5 VARCHAR(2),
    dur_lvl_of_effort_6 VARCHAR(2),
    dur_reason_service_6 VARCHAR(2),
    dur_prof_service_code_6 VARCHAR(2),
    dur_result_of_serv_cd_6 VARCHAR(2),
    dur_lvl_of_effort_7 VARCHAR(2),
    dur_reason_service_7 VARCHAR(2),
    dur_prof_service_code_7 VARCHAR(2),
    dur_result_of_serv_cd_7 VARCHAR(2),
    dur_lvl_of_effort_8 VARCHAR(2),
    dur_reason_service_8 VARCHAR(2),
    dur_prof_service_code_8 VARCHAR(2),
    dur_result_of_serv_cd_8 VARCHAR(2),
    dur_lvl_of_effort_9 VARCHAR(2),
    dur_reason_service_9 VARCHAR(2),
    dur_prof_service_code_9 VARCHAR(2),
    dur_result_of_serv_cd_9 VARCHAR(2),
    scd_claim VARCHAR(1),
    thresh_5100 NUMERIC(18, 2),
    c_formulary_id_flag VARCHAR(1),
    brand_config_occur BIGINT,
    card_id_sent_from_pharm VARCHAR(20),
    hms_physician_id VARCHAR(10),
    tier VARCHAR(1),
    claim_adjudication_time VARCHAR(26),
    age BIGINT,
    quantity_dispensed NUMERIC(18, 3),
    previous_restack_batch VARCHAR(8),
    previous_restack_claim BIGINT,
    wac_ref_price NUMERIC(18, 2),
    specialty_flag VARCHAR(1),
    mail_order_indication VARCHAR(4),
    spcl_patient_disp_fee NUMERIC(18, 2),
    hms_poid VARCHAR(10),
    orig_rev_batch VARCHAR(8),
    orig_rev_claim BIGINT,
    grp_broker_nbr VARCHAR(4),
    payment_center_id VARCHAR(6),
    remit_reconciliation_id VARCHAR(6),
    pdmi_reject_code_1 VARCHAR(4),
    pdmi_reject_code_2 VARCHAR(4),
    pdmi_reject_code_3 VARCHAR(4),
    pdmi_reject_code_4 VARCHAR(4),
    pdmi_reject_code_5 VARCHAR(4),
    pdmi_reject_code_6 VARCHAR(4),
    pdmi_reject_code_7 VARCHAR(4),
    pdmi_reject_code_8 VARCHAR(4),
    pdmi_reject_code_9 VARCHAR(4),
    pdmi_reject_code_10 VARCHAR(4),
    pdmi_reject_code_11 VARCHAR(4),
    pdmi_reject_code_12 VARCHAR(4),
    pdmi_reject_code_13 VARCHAR(4),
    pdmi_reject_code_14 VARCHAR(4),
    pdmi_reject_code_15 VARCHAR(4),
    pdmi_reject_code_16 VARCHAR(4),
    pdmi_reject_code_17 VARCHAR(4),
    pdmi_reject_code_18 VARCHAR(4),
    pdmi_reject_code_19 VARCHAR(4),
    pdmi_reject_code_20 VARCHAR(4),
    amount_applied_to_oop NUMERIC(18, 2),
    n1_claim_key VARCHAR(14),
    n1_batch_number VARCHAR(8),
    n1_claim_number BIGINT,
    user_id VARCHAR(15),
    opioid_factor NUMERIC(18, 2),
    contract_chain_number BIGINT,
    differential_claim_type VARCHAR(6),
    carrier_id VARCHAR(10),
    pharm_electronic_fee NUMERIC(18, 2),
    vaccine_admin_fee NUMERIC(18, 2),
    prescriber_id_qualifier VARCHAR(10),
    ctree_toggle VARCHAR(1),
    orig_med_gen_code VARCHAR(1),
    oth_pay_covg_type VARCHAR(2),
    script_care_claim VARCHAR(1),
    script_care_net_pricing VARCHAR(1),
    quantity_prescribed NUMERIC(18, 3),
    pdmi_admin_fee NUMERIC(18, 2),
    client_sys_spo_admin_fee NUMERIC(18, 2),
    client_spo_grp_admin_fee NUMERIC(18, 2),
    claim_category VARCHAR(12),
    client_basis_of_cost VARCHAR(2),
    pharm_basis_of_cost VARCHAR(2),
    group_from_pharm VARCHAR(15),
    tax_exempt_flag CHAR(1),
    network_reimb_id VARCHAR(10),
    copay_n1_amount NUMERIC(18, 2),
    calcamtpaid NUMERIC(23, 2)
);
