-- =============================================
-- Table: cloud_data_warehouse.claims_accum
-- Columns: 313
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.claims_accum (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_src_sys_nm VARCHAR(80),
    meta_iud_flg VARCHAR(1),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    batch_master VARCHAR(8),
    claim_number INTEGER,
    claim_type VARCHAR(1),
    original_batch_key VARCHAR(8),
    original_claim_number INTEGER,
    limit_number NUMERIC(19, 0),
    limit_member_number INTEGER,
    limit_bin INTEGER,
    limit_rollup_code VARCHAR(20),
    limit_roll_date TIMESTAMP,
    limit_number_s NUMERIC(19, 0),
    limit_member_number_s INTEGER,
    limit_bin_s INTEGER,
    limit_rollup_code_s VARCHAR(20),
    limit_roll_date_s TIMESTAMP,
    copay_system_number INTEGER,
    copay_sponsor_number INTEGER,
    copay_schedule_number VARCHAR(4),
    copay_schedule_type VARCHAR(6),
    reimb_rate_number INTEGER,
    reimb_rate_gen_type VARCHAR(6),
    except_cardholder_number VARCHAR(10),
    except_member_number VARCHAR(2),
    except_bin INTEGER,
    except_gpi VARCHAR(14),
    pharm_net_network_number INTEGER,
    pharm_net_nabp_number INTEGER,
    pharm_net_state_code INTEGER,
    plan_system_number INTEGER,
    plan_number VARCHAR(8),
    specialty_table_id VARCHAR(8),
    specialty_gpi VARCHAR(14),
    specialty_config_table_id VARCHAR(8),
    specialty_config_gpi VARCHAR(14),
    specialty_config_eff_date TIMESTAMP,
    spcfds_specialty_config_id VARCHAR(8),
    sptds_specialty_table_id VARCHAR(8),
    tpm_system_number INTEGER,
    tpm_sponsor_number INTEGER,
    tpm_group_number NUMERIC(19, 0),
    tpm_rec_type INTEGER,
    tpm_sequence_number INTEGER,
    dift_t_link VARCHAR(5),
    dift_system_number INTEGER,
    dift_sponsor_number INTEGER,
    dift_group_number NUMERIC(19, 0),
    dift_network_number INTEGER,
    dift_nabp INTEGER,
    dift_gpi VARCHAR(14),
    dift_ndc NUMERIC(19, 0),
    dift_claim_type VARCHAR(6),
    dift_table_number INTEGER,
    dift_date_type VARCHAR(2),
    dift_sequence_number INTEGER,
    cfg_t_link VARCHAR(5),
    cfg_system_number INTEGER,
    cfg_sponsor_number INTEGER,
    cfg_group_number NUMERIC(19, 0),
    cfg_rec_type VARCHAR(3),
    cfg_date_type VARCHAR(2),
    cfg_data_type VARCHAR(3),
    cfg_data VARCHAR(20),
    cfg_amt_type VARCHAR(3),
    cfg_occ INTEGER,
    cfg_min_amt NUMERIC(18, 4),
    cfg_max_amt NUMERIC(18, 4),
    cfg_sequence_number INTEGER,
    ruc_t_link VARCHAR(5),
    ruc_system_number INTEGER,
    ruc_sponsor_number INTEGER,
    ruc_group_number NUMERIC(19, 0),
    ruc_sequence_number INTEGER,
    ruc_t_link_s VARCHAR(5),
    ruc_system_number_s INTEGER,
    ruc_sponsor_number_s INTEGER,
    ruc_group_number_s NUMERIC(19, 0),
    ruc_sequence_number_s INTEGER,
    rcp_rollup_code VARCHAR(20),
    rcp_sequence_number INTEGER,
    nsde_ndc NUMERIC(19, 0),
    nsdeor_system_number INTEGER,
    nsdeor_sponsor_number INTEGER,
    nsdeor_group_number NUMERIC(19, 0),
    nsdeor_plan VARCHAR(8),
    nsdeor_cardholder_number VARCHAR(10),
    nsdeor_member_number VARCHAR(2),
    nsdeor_ndc NUMERIC(19, 0),
    nsdeor_gpi VARCHAR(14),
    nsdeor_sequence_number INTEGER,
    nm_ndc NUMERIC(19, 0),
    ndc_ovr_ndc_id VARCHAR(8),
    ndc_ovr_ndc NUMERIC(19, 0),
    ndc_ovr_sequence_number INTEGER,
    nloc_sponsor_number INTEGER,
    nloc_group_number FLOAT8,
    nloc_ndc NUMERIC(19, 0),
    fvss_batch_master VARCHAR(8),
    fvss_claim_number INTEGER,
    fvss_claim_type VARCHAR(1),
    brc_brand_id VARCHAR(20),
    brc_multi_use_one_time_flag VARCHAR(1),
    brc_rx_date TIMESTAMP,
    brc_todays_date TIMESTAMP,
    brc_pharmacy_state_code VARCHAR(2),
    brc_pharmacy_zip_code VARCHAR(9),
    brc_chain INTEGER,
    brc_nabp_number INTEGER,
    brc_ndc NUMERIC(38, 0),
    brc_gpi VARCHAR(14),
    brc_oth_cov_code INTEGER,
    brc_compu_days_supply INTEGER,
    brc_compu_met_quant NUMERIC(18, 3),
    brc_compu_redemp_count INTEGER,
    brc_compu_sponsor_number INTEGER,
    brc_config_type VARCHAR(1),
    brc_cob_flag VARCHAR(1),
    brc_cob38_flag VARCHAR(1),
    brc_cob8_only_flag VARCHAR(1),
    brc_srts_flag VARCHAR(1),
    brc_min_copay_flag VARCHAR(1),
    brc_limits_apply_flag VARCHAR(1),
    brc_skip212_reject_flag VARCHAR(1),
    brc_apply275_reject_flag VARCHAR(1),
    brc_apply538_reject_flag VARCHAR(1),
    brc_skip232_reject_flag VARCHAR(1),
    brc_brchn_reject VARCHAR(1),
    brc_brben_ds_reject VARCHAR(1),
    brc_brben_mq_reject VARCHAR(1),
    brc_mass_primary_reject_flag VARCHAR(1),
    brc_mass_cob_reject_flag VARCHAR(1),
    brc_no_mass_reject_flag VARCHAR(1),
    brc_missing_brcfg_reject VARCHAR(1),
    brc_missing_brben_reject VARCHAR(1),
    brc_occurence INTEGER,
    brc_copay NUMERIC(18, 2),
    brc_max_claim_amt NUMERIC(18, 2),
    brc_error_status_code VARCHAR(2),
    brc_error_file VARCHAR(10),
    brc_error_flag VARCHAR(1),
    brc_rejected_occ INTEGER,
    brc_pharm_rules_reject_flag VARCHAR(1),
    brc_bilo_winn_rules_reject_flag VARCHAR(1),
    brc_apply249_reject_flag VARCHAR(1),
    disp_mq_multi NUMERIC(18, 3),
    ws_qty_mult_message VARCHAR(1),
    brc_brben_term_flag VARCHAR(1),
    crd_coverage_type VARCHAR(1),
    pl_max_single NUMERIC(18, 2),
    pl_max_family NUMERIC(18, 2),
    pl_ded_single NUMERIC(18, 2),
    pl_ded_family NUMERIC(18, 2),
    pl_sing_max NUMERIC(18, 2),
    pl_family_max NUMERIC(18, 2),
    pl_lifetime_max NUMERIC(18, 2),
    pl_troop_amt NUMERIC(18, 2),
    grp_broker_number VARCHAR(4),
    grp_limit_kind VARCHAR(1),
    limit_mbr_max NUMERIC(18, 2),
    single_copay NUMERIC(18, 2),
    single_copay_max NUMERIC(18, 2),
    single_copay_ded NUMERIC(18, 2),
    family_copay NUMERIC(18, 2),
    family_copay_max NUMERIC(18, 2),
    family_copay_ded NUMERIC(18, 2),
    limit_paid NUMERIC(18, 2),
    limit_paid_mail NUMERIC(18, 2),
    max_left NUMERIC(18, 2),
    max_j_paid NUMERIC(18, 2),
    max_j_left NUMERIC(18, 2),
    max_paid NUMERIC(18, 2),
    max_paid_mail NUMERIC(18, 2),
    limit_claims_before INTEGER,
    limit_t_ing_bill_before NUMERIC(18, 2),
    limit_t_copay_before NUMERIC(18, 2),
    limit_t_disp_before NUMERIC(18, 2),
    limit_t_tax_before NUMERIC(18, 2),
    limit_t_ing_paid_before NUMERIC(18, 2),
    limit_last_qtr_carry_over_before NUMERIC(18, 2),
    limit_m_claims_before INTEGER,
    limit_m_ing_bill_before NUMERIC(18, 2),
    limit_m_copay_before NUMERIC(18, 2),
    limit_m_disp_before NUMERIC(18, 2),
    limit_m_tax_before NUMERIC(18, 2),
    limit_m_ing_paid_before NUMERIC(18, 2),
    limit_last_qtr_carry_over_mail_before NUMERIC(18, 2),
    limit_ded_amt_only_before NUMERIC(18, 2),
    limit_med_d_non_lics_ded_amt_before NUMERIC(18, 2),
    limit_troop_amt_before NUMERIC(18, 2),
    limit_tot_drug2250_before NUMERIC(18, 2),
    limit_stand_ded_only_before NUMERIC(18, 2),
    ex_occurrence_before INTEGER,
    ex_max_dollar_before NUMERIC(18, 2),
    ex_max_dollar_to_date_before NUMERIC(18, 2),
    limit_claims_bs INTEGER,
    limit_t_ing_bill_bs NUMERIC(18, 2),
    limit_t_copay_bs NUMERIC(18, 2),
    limit_t_disp_bs NUMERIC(18, 2),
    limit_t_tax_bs NUMERIC(18, 2),
    limit_t_ing_paid_bs NUMERIC(18, 2),
    limit_last_qtr_carry_over_bs NUMERIC(18, 2),
    limit_m_claims_bs INTEGER,
    limit_m_ing_bill_bs NUMERIC(18, 2),
    limit_m_copay_bs NUMERIC(18, 2),
    limit_m_disp_bs NUMERIC(18, 2),
    limit_m_tax_bs NUMERIC(18, 2),
    limit_m_ing_paid_bs NUMERIC(18, 2),
    limit_last_qtr_carry_over_mail_bs NUMERIC(18, 2),
    limit_ded_amt_only_bs NUMERIC(18, 2),
    limit_med_d_non_lics_ded_amt_bs NUMERIC(18, 2),
    limit_troop_amt_bs NUMERIC(18, 2),
    limit_tot_drug2250_bs NUMERIC(18, 2),
    limit_stand_ded_only_bs NUMERIC(18, 2),
    limit_claims_after INTEGER,
    limit_t_ing_bill_after NUMERIC(18, 2),
    limit_t_copay_after NUMERIC(18, 2),
    limit_t_disp_after NUMERIC(18, 2),
    limit_t_tax_after NUMERIC(18, 2),
    limit_t_ing_paid_after NUMERIC(18, 2),
    limit_last_qtr_carry_over_after NUMERIC(18, 2),
    limit_m_claims_after INTEGER,
    limit_m_ing_bill_after NUMERIC(18, 2),
    limit_m_copay_after NUMERIC(18, 2),
    limit_m_disp_after NUMERIC(18, 2),
    limit_m_tax_after NUMERIC(18, 2),
    limit_m_ing_paid_after NUMERIC(18, 2),
    limit_last_qtr_carry_over_mail_after NUMERIC(18, 2),
    limit_ded_amt_only_after NUMERIC(18, 2),
    limit_med_d_non_lics_ded_amt_after NUMERIC(18, 2),
    limit_troop_amt_after NUMERIC(18, 2),
    limit_tot_drug2250_after NUMERIC(18, 2),
    limit_stand_ded_only_after NUMERIC(18, 2),
    ex_occurrence_after INTEGER,
    ex_max_dollar_after NUMERIC(18, 2),
    ex_max_dollar_to_date_after NUMERIC(18, 2),
    limit_claims_as INTEGER,
    limit_t_ing_bill_as NUMERIC(18, 2),
    limit_t_copay_as NUMERIC(18, 2),
    limit_t_disp_as NUMERIC(18, 2),
    limit_t_tax_as NUMERIC(18, 2),
    limit_t_ing_paid_as NUMERIC(18, 2),
    limit_last_qtr_carry_over_as NUMERIC(18, 2),
    limit_m_claims_as INTEGER,
    limit_m_ing_bill_as NUMERIC(18, 2),
    limit_m_copay_as NUMERIC(18, 2),
    limit_m_disp_as NUMERIC(18, 2),
    limit_m_tax_as NUMERIC(18, 2),
    limit_m_ing_paid_as NUMERIC(18, 2),
    limit_last_qtr_carry_over_mail_as NUMERIC(18, 2),
    limit_ded_amt_only_as NUMERIC(18, 2),
    limit_med_d_non_lics_ded_amt_as NUMERIC(18, 2),
    limit_troop_amt_as NUMERIC(18, 2),
    limit_tot_drug2250_as NUMERIC(18, 2),
    limit_stand_ded_only_as NUMERIC(18, 2),
    oop_single_limit NUMERIC(18, 2),
    oop_family_limit NUMERIC(18, 2),
    ded_single_limit NUMERIC(18, 2),
    ded_family_limit NUMERIC(18, 2),
    oop_single_app_amt NUMERIC(18, 2),
    oop_family_app_amt NUMERIC(18, 2),
    ded_single_app_amt NUMERIC(18, 2),
    ded_family_app_amt NUMERIC(18, 2),
    oop_single_app_amt_ytd NUMERIC(18, 2),
    oop_family_app_amt_ytd NUMERIC(18, 2),
    ded_single_app_amt_ytd NUMERIC(18, 2),
    ded_family_app_amt_ytd NUMERIC(18, 2),
    nsde_eff_date TIMESTAMP,
    nsde_term_date TIMESTAMP,
    ndc_loc_eff_date TIMESTAMP,
    ndc_loc_term_date TIMESTAMP,
    plan_specialty_config_id VARCHAR(8),
    plan_specialty_table_id VARCHAR(8),
    vrx_action_code VARCHAR(8),
    enroll_begin_date TIMESTAMP,
    enroll_term_date TIMESTAMP,
    enroll_use_date TIMESTAMP,
    nppes_begin_date TIMESTAMP,
    nppes_term_date TIMESTAMP,
    prov_fill_ind VARCHAR(2),
    pdmi_result VARCHAR(1),
    ef_result VARCHAR(1),
    ef_excep_code VARCHAR(1),
    ef_value_type VARCHAR(1),
    form_ndc_id VARCHAR(8),
    plan_ndc_id VARCHAR(8),
    res_uid VARCHAR(36),
    res_prod_type VARCHAR(20),
    res_response_code VARCHAR(10),
    res_response_msg VARCHAR(200),
    res_pharm_msg VARCHAR(200),
    res_ing_cost NUMERIC(18, 2),
    res_disp_fee NUMERIC(18, 2),
    res_copay_amt_ovr NUMERIC(18, 2),
    res_tax NUMERIC(18, 2),
    res_pdmi_reject_ovr VARCHAR(10),
    res_source_sys_id VARCHAR(36),
    res_pi_id VARCHAR(10),
    file_date TIMESTAMP,
    add_id VARCHAR(15),
    change_id VARCHAR(15),
    add_date TIMESTAMP,
    change_date TIMESTAMP,
    claim_key VARCHAR(14),
    original_claim_key VARCHAR(14),
    copay_key VARCHAR(12),
    pharm_net_key VARCHAR(16),
    plan_key VARCHAR(16)
);
