-- =============================================
-- Table: cloud_data_warehouse.claims_msg_cob
-- Columns: 52
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.claims_msg_cob (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_src_sys_nm VARCHAR(80),
    meta_iud_flg VARCHAR(1),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    batch_master VARCHAR(8),
    claim_number INTEGER,
    segment_id VARCHAR(4),
    seq_id INTEGER,
    cnt INTEGER,
    cov_type_1 VARCHAR(2),
    id_qual_1 VARCHAR(2),
    bin_1 VARCHAR(10),
    pcn_1 VARCHAR(10),
    card_id_1 VARCHAR(20),
    group_id_1 VARCHAR(15),
    person_code_1 VARCHAR(3),
    phone_number_1 VARCHAR(13),
    cov_type_2 VARCHAR(2),
    id_qual_2 VARCHAR(2),
    bin_2 VARCHAR(10),
    pcn_2 VARCHAR(10),
    card_id_2 VARCHAR(20),
    group_id_2 VARCHAR(15),
    person_code_2 VARCHAR(3),
    phone_number_2 VARCHAR(13),
    cov_type_3 VARCHAR(2),
    id_qual_3 VARCHAR(2),
    bin_3 VARCHAR(10),
    pcn_3 VARCHAR(10),
    card_id_3 VARCHAR(20),
    group_id_3 VARCHAR(15),
    person_code_3 VARCHAR(3),
    phone_number_3 VARCHAR(13),
    cov_type_4 VARCHAR(2),
    id_qual_4 VARCHAR(2),
    bin_4 VARCHAR(10),
    pcn_4 VARCHAR(10),
    card_id_4 VARCHAR(20),
    group_id_4 VARCHAR(15),
    person_code_4 VARCHAR(3),
    phone_number_4 VARCHAR(13),
    cov_type_5 VARCHAR(2),
    id_qual_5 VARCHAR(2),
    bin_5 VARCHAR(10),
    pcn_5 VARCHAR(10),
    card_id_5 VARCHAR(20),
    group_id_5 VARCHAR(15),
    person_code_5 VARCHAR(3),
    phone_number_5 VARCHAR(13)
);
