-- =============================================
-- Table: cloud_data_warehouse.drug_data
-- Columns: 168
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.drug_data (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_src_sys_nm VARCHAR(80),
    meta_iud_flg VARCHAR(1),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    drug_key VARCHAR(15),
    ndc_type_code BIGINT,
    ndc VARCHAR(11),
    gpi VARCHAR(14),
    prod_abbr VARCHAR(25),
    generic_code VARCHAR(1),
    thera_class BIGINT,
    rx_otc_code VARCHAR(1),
    dea_code VARCHAR(5),
    prod VARCHAR(12),
    awp_price_1 NUMERIC(18, 5),
    awp_date_1 DATE,
    awp_price_2 NUMERIC(18, 5),
    awp_date_2 DATE,
    awp_price_3 NUMERIC(18, 5),
    awp_date_3 DATE,
    awp_price_4 NUMERIC(18, 5),
    awp_date_4 DATE,
    mac_price_1 NUMERIC(18, 5),
    manuf_name_abbr VARCHAR(10),
    thera_equiv VARCHAR(2),
    legend_change_date DATE,
    desi VARCHAR(1),
    third_party_code VARCHAR(1),
    act_code VARCHAR(1),
    package_size NUMERIC(18, 3),
    route_admin VARCHAR(2),
    dosage_form VARCHAR(4),
    ter_date DATE,
    prior_auth_flag VARCHAR(1),
    brand_name_code VARCHAR(1),
    mac_date_1 DATE,
    mac_price_2 NUMERIC(18, 5),
    mac_date_2 DATE,
    maint_code VARCHAR(1),
    reimb_code VARCHAR(1),
    labeler_type_code VARCHAR(1),
    wholesaler_acquisition_cost NUMERIC(18, 6),
    inner_pack_code VARCHAR(1),
    clinic_pack_code VARCHAR(1),
    price_spread_code VARCHAR(1),
    status_flag VARCHAR(1),
    unit_cost_factor NUMERIC(18, 3),
    progen_rebate VARCHAR(1),
    brand_multi_combo VARCHAR(2),
    sponsor_number BIGINT,
    dollar_rank VARCHAR(1),
    rx_rank VARCHAR(1),
    single_combination_code VARCHAR(1),
    ppg_indicator_code VARCHAR(1),
    hfpg_indicator_code VARCHAR(1),
    drug_name_code VARCHAR(6),
    metric_strength NUMERIC(18, 3),
    size_u_m VARCHAR(2),
    next_smaller_suffix BIGINT,
    next_larger_suffix BIGINT,
    dp_price_code VARCHAR(1),
    dp_pack_price_1 NUMERIC(18, 2),
    dp_pack_price_2 NUMERIC(18, 2),
    dp_pack_price_3 NUMERIC(18, 2),
    dp_pack_price_4 NUMERIC(18, 2),
    pre_by_identification_number VARCHAR(12),
    sup_by_identification_number VARCHAR(12),
    drug_effective_date DATE,
    drug_dps_effective_date_1 DATE,
    drug_dps_effective_date_2 DATE,
    drug_dps_effective_date_3 DATE,
    drug_dps_termination_date_1 DATE,
    drug_dps_termination_date_2 DATE,
    drug_dps_termination_date_3 DATE,
    ddi_patient_code BIGINT,
    pcm_patient_code BIGINT,
    allergy_patient_code BIGINT,
    drug_error_record VARCHAR(3),
    drug_error_date DATE,
    drug_reimbursement_schedule VARCHAR(6),
    drug_copay_schedule_type VARCHAR(6),
    drug_quantity_limit NUMERIC(18, 3),
    repack_flag VARCHAR(1),
    drug_awp_litigation VARCHAR(1),
    drug_app_type VARCHAR(1),
    drug_app_type_source VARCHAR(1),
    kdc_1 BIGINT,
    kdc_2 BIGINT,
    kdc_3 BIGINT,
    gen_cross_ref_type_cd VARCHAR(1),
    gen_id_no VARCHAR(10),
    disp_unit VARCHAR(1),
    unit_dose VARCHAR(1),
    prod_name VARCHAR(25),
    mac_prc_cd VARCHAR(1),
    awp_prc_cd VARCHAR(1),
    awp_pack_price_1 NUMERIC(18, 2),
    awp_pack_price_2 NUMERIC(18, 2),
    awp_pack_price_3 NUMERIC(18, 2),
    awp_pack_price_4 NUMERIC(18, 2),
    source VARCHAR(15),
    gppc VARCHAR(8),
    medispan_key VARCHAR(12),
    dd_act_code VARCHAR(1),
    last_change_notes VARCHAR(30),
    first_data_gcn_number VARCHAR(5),
    first_data_gi VARCHAR(1),
    first_data_gpi VARCHAR(1),
    type_code_16 VARCHAR(1),
    fda_non_touch VARCHAR(1),
    type_code_32 VARCHAR(1),
    type_code_33 VARCHAR(1),
    canadian_drug_id VARCHAR(8),
    canada_margin_1 NUMERIC(18, 5),
    canada_eff_date_1 DATE,
    canada_margin_2 NUMERIC(18, 5),
    canada_eff_date_2 DATE,
    canada_margin_3 NUMERIC(18, 5),
    canada_eff_date_3 DATE,
    canada_margin_4 NUMERIC(18, 5),
    canada_eff_date_4 DATE,
    canada_margin_5 NUMERIC(18, 5),
    canada_eff_date_5 DATE,
    dpc_cd VARCHAR(3),
    ppc_cd VARCHAR(3),
    limited_distr_cd VARCHAR(2),
    awp_pack_price_5 NUMERIC(18, 2),
    awp_price_5 NUMERIC(18, 5),
    awp_date_5 DATE,
    awp_pack_price_6 NUMERIC(18, 2),
    awp_price_6 NUMERIC(18, 5),
    awp_date_6 DATE,
    whlsr_pk_cost NUMERIC(18, 2),
    whlsr_eff_date DATE,
    whlsr_acquisition_cost_2 NUMERIC(18, 5),
    whlsr_pk_cost_2 NUMERIC(18, 2),
    whlsr_eff_date_2 DATE,
    delivery_mult_qty_flag VARCHAR(1),
    abridged_ind VARCHAR(1),
    comprehensive_ind VARCHAR(1),
    brand_id VARCHAR(20),
    notes_1 VARCHAR(40),
    notes_2 VARCHAR(40),
    system_number BIGINT,
    man_date DATE,
    medi_date DATE,
    whlsr_acquisition_cost_3 NUMERIC(18, 5),
    whlsr_pk_cost_3 NUMERIC(18, 2),
    whlsr_eff_date_3 DATE,
    whlsr_acquisition_cost_4 NUMERIC(18, 5),
    whlsr_pk_cost_4 NUMERIC(18, 2),
    whlsr_eff_date_4 DATE,
    whlsr_acquisition_cost_5 NUMERIC(18, 5),
    whlsr_pk_cost_5 NUMERIC(18, 2),
    whlsr_eff_date_5 DATE,
    whlsr_acquisition_cost_6 NUMERIC(18, 5),
    whlsr_pk_cost_6 NUMERIC(18, 2),
    whlsr_eff_date_6 DATE,
    mod_code VARCHAR(6),
    mac_pack_price_1 NUMERIC(18, 2),
    mac_pack_price_2 NUMERIC(18, 2),
    orig_med_gen_code VARCHAR(1),
    cfg_add_id VARCHAR(15),
    cfg_change_id VARCHAR(15),
    ndc_action VARCHAR(1)
);
