-- =============================================
-- Table: cloud_data_warehouse.drug_pricing
-- Columns: 134
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.drug_pricing (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_src_sys_nm VARCHAR(80),
    meta_iud_flg VARCHAR(1),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    drug_key VARCHAR(15),
    ndc_type_code INTEGER,
    ndc NUMERIC(11, 0),
    awp_pack_price_1 NUMERIC(18, 2),
    awp_unit_price_1 NUMERIC(18, 5),
    awp_eff_date_1 DATE,
    awp_term_date_1 DATE,
    awp_pack_price_2 NUMERIC(18, 2),
    awp_unit_price_2 NUMERIC(18, 5),
    awp_eff_date_2 DATE,
    awp_term_date_2 DATE,
    awp_pack_price_3 NUMERIC(18, 2),
    awp_unit_price_3 NUMERIC(18, 5),
    awp_eff_date_3 DATE,
    awp_term_date_3 DATE,
    awp_pack_price_4 NUMERIC(18, 2),
    awp_unit_price_4 NUMERIC(18, 5),
    awp_eff_date_4 DATE,
    awp_term_date_4 DATE,
    awp_pack_price_5 NUMERIC(18, 2),
    awp_unit_price_5 NUMERIC(18, 5),
    awp_eff_date_5 DATE,
    awp_term_date_5 DATE,
    awp_pack_price_6 NUMERIC(18, 2),
    awp_unit_price_6 NUMERIC(18, 5),
    awp_eff_date_6 DATE,
    awp_term_date_6 DATE,
    mac_pack_price_1 NUMERIC(18, 2),
    mac_unit_price_1 NUMERIC(18, 5),
    mac_eff_date_1 DATE,
    mac_term_date_1 DATE,
    mac_pack_price_2 NUMERIC(18, 2),
    mac_unit_price_2 NUMERIC(18, 5),
    mac_eff_date_2 DATE,
    mac_term_date_2 DATE,
    mac_pack_price_3 NUMERIC(18, 2),
    mac_unit_price_3 NUMERIC(18, 5),
    mac_eff_date_3 DATE,
    mac_term_date_3 DATE,
    mac_pack_price_4 NUMERIC(18, 2),
    mac_unit_price_4 NUMERIC(18, 5),
    mac_eff_date_4 DATE,
    mac_term_date_4 DATE,
    mac_pack_price_5 NUMERIC(18, 2),
    mac_unit_price_5 NUMERIC(18, 5),
    mac_eff_date_5 DATE,
    mac_term_date_5 DATE,
    mac_pack_price_6 NUMERIC(18, 2),
    mac_unit_price_6 NUMERIC(18, 5),
    mac_eff_date_6 DATE,
    mac_term_date_6 DATE,
    wac_pack_price_1 NUMERIC(18, 2),
    wac_unit_price_1 NUMERIC(18, 5),
    wac_eff_date_1 DATE,
    wac_term_date_1 DATE,
    wac_pack_price_2 NUMERIC(18, 2),
    wac_unit_price_2 NUMERIC(18, 5),
    wac_eff_date_2 DATE,
    wac_term_date_2 DATE,
    wac_pack_price_3 NUMERIC(18, 2),
    wac_unit_price_3 NUMERIC(18, 5),
    wac_eff_date_3 DATE,
    wac_term_date_3 DATE,
    wac_pack_price_4 NUMERIC(18, 2),
    wac_unit_price_4 NUMERIC(18, 5),
    wac_eff_date_4 DATE,
    wac_term_date_4 DATE,
    wac_pack_price_5 NUMERIC(18, 2),
    wac_unit_price_5 NUMERIC(18, 5),
    wac_eff_date_5 DATE,
    wac_term_date_5 DATE,
    wac_pack_price_6 NUMERIC(18, 2),
    wac_unit_price_6 NUMERIC(18, 5),
    wac_eff_date_6 DATE,
    wac_term_date_6 DATE,
    nadac_pack_price_1 NUMERIC(18, 2),
    nadac_unit_price_1 NUMERIC(18, 5),
    nadac_eff_date_1 DATE,
    nadac_term_date_1 DATE,
    nadac_pack_price_2 NUMERIC(18, 2),
    nadac_unit_price_2 NUMERIC(18, 5),
    nadac_eff_date_2 DATE,
    nadac_term_date_2 DATE,
    nadac_pack_price_3 NUMERIC(18, 2),
    nadac_unit_price_3 NUMERIC(18, 5),
    nadac_eff_date_3 DATE,
    nadac_term_date_3 DATE,
    nadac_pack_price_4 NUMERIC(18, 2),
    nadac_unit_price_4 NUMERIC(18, 5),
    nadac_eff_date_4 DATE,
    nadac_term_date_4 DATE,
    nadac_pack_price_5 NUMERIC(18, 2),
    nadac_unit_price_5 NUMERIC(18, 5),
    nadac_eff_date_5 DATE,
    nadac_term_date_5 DATE,
    nadac_pack_price_6 NUMERIC(18, 2),
    nadac_unit_price_6 NUMERIC(18, 5),
    nadac_eff_date_6 DATE,
    nadac_term_date_6 DATE,
    mccpp_pack_price_1 NUMERIC(18, 2),
    mccpp_unit_price_1 NUMERIC(18, 5),
    mccpp_eff_date_1 DATE,
    mccpp_term_date_1 DATE,
    mccpp_pack_price_2 NUMERIC(18, 2),
    mccpp_unit_price_2 NUMERIC(18, 5),
    mccpp_eff_date_2 DATE,
    mccpp_term_date_2 DATE,
    mccpp_pack_price_3 NUMERIC(18, 2),
    mccpp_unit_price_3 NUMERIC(18, 5),
    mccpp_eff_date_3 DATE,
    mccpp_term_date_3 DATE,
    mccpp_pack_price_4 NUMERIC(18, 2),
    mccpp_unit_price_4 NUMERIC(18, 5),
    mccpp_eff_date_4 DATE,
    mccpp_term_date_4 DATE,
    mccpp_pack_price_5 NUMERIC(18, 2),
    mccpp_unit_price_5 NUMERIC(18, 5),
    mccpp_eff_date_5 DATE,
    mccpp_term_date_5 DATE,
    mccpp_pack_price_6 NUMERIC(18, 2),
    mccpp_unit_price_6 NUMERIC(18, 5),
    mccpp_eff_date_6 DATE,
    mccpp_term_date_6 DATE,
    add_date DATE,
    change_date DATE,
    add_id VARCHAR(15),
    change_id VARCHAR(15)
);
