-- =============================================
-- Table: cloud_data_warehouse.exceptions_tmp
-- Columns: 51
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.exceptions_tmp (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_src_sys_nm VARCHAR(80),
    meta_iud_flg VARCHAR(1),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    cardholder_number VARCHAR(10),
    member_number VARCHAR(2),
    sponsor BIGINT,
    gpi VARCHAR(14),
    cardholder_key VARCHAR(20),
    eff_date_1 DATE,
    eff_date_2 DATE,
    eff_date_3 DATE,
    eff_date_4 DATE,
    eff_date_5 DATE,
    term_date_1 DATE,
    term_date_2 DATE,
    term_date_3 DATE,
    term_date_4 DATE,
    term_date_5 DATE,
    pharmacy_number BIGINT,
    chain_number BIGINT,
    physician_number VARCHAR(10),
    days_supply BIGINT,
    metric_quantity NUMERIC(18, 3),
    type_code BIGINT,
    ndc VARCHAR(11),
    copay_override BIGINT,
    reason VARCHAR(60),
    max_dollar BIGINT,
    max_dollar_to_date NUMERIC(18, 2),
    occurence BIGINT,
    no_maximum VARCHAR(1),
    user VARCHAR(12),
    max_dl_1 BIGINT,
    max_dl_2 BIGINT,
    max_dl_3 BIGINT,
    max_dl_4 BIGINT,
    max_to_date_1 NUMERIC(18, 2),
    max_to_date_2 NUMERIC(18, 2),
    max_to_date_3 NUMERIC(18, 2),
    max_to_date_4 NUMERIC(18, 2),
    occur_1 BIGINT,
    occur_2 BIGINT,
    occur_3 BIGINT,
    occur_4 BIGINT,
    med_code VARCHAR(1),
    enter_date DATE,
    change_date DATE
);
