-- =============================================
-- Table: cloud_data_warehouse.first_view_claims
-- Columns: 54
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.first_view_claims (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_src_sys_nm VARCHAR(80),
    meta_iud_flg VARCHAR(1),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    batch_master VARCHAR(8),
    claim_number INTEGER,
    claim_type VARCHAR(1),
    other_cov_code_orig INTEGER,
    other_cov_code_proc INTEGER,
    copay_orig NUMERIC(18, 4),
    rej_code_1 INTEGER,
    rej_code_2 INTEGER,
    req_bin INTEGER,
    req_pcn VARCHAR(10),
    req_claim_uid VARCHAR(36),
    req_pharmacy VARCHAR(15),
    req_group_nbr VARCHAR(15),
    req_rx_nbr INTEGER,
    req_rx_date TIMESTAMP,
    req_ndc NUMERIC(12, 0),
    req_met_qty NUMERIC(18, 3),
    req_days_supply INTEGER,
    req_pri_copay_amt NUMERIC(18, 2),
    req_pri_amt_paid NUMERIC(18, 2),
    req_flat_sales_tax NUMERIC(18, 2),
    req_sales_tax_rate NUMERIC(18, 4),
    req_sales_tax_basis NUMERIC(18, 4),
    req_unr_charge NUMERIC(18, 2),
    req_cardholder VARCHAR(20),
    req_patient_dob TIMESTAMP,
    req_physician VARCHAR(15),
    req_oth_cov_code INTEGER,
    res_uid VARCHAR(36),
    res_product_type VARCHAR(20),
    res_response_code VARCHAR(10),
    res_response_msg VARCHAR(200),
    res_pharmacy_msg VARCHAR(200),
    res_ing_cost NUMERIC(18, 2),
    res_disp_fee NUMERIC(18, 2),
    res_copay_amt_ovr NUMERIC(18, 2),
    res_tax NUMERIC(18, 2),
    res_pdmi_reject_ovr VARCHAR(10),
    resource_sys_id VARCHAR(36),
    res_piid VARCHAR(10),
    raw_payload VARCHAR(2048),
    add_to_file_date_time TIMESTAMP,
    add_id VARCHAR(15),
    change_id VARCHAR(15),
    add_date TIMESTAMP,
    change_date TIMESTAMP,
    claim_key VARCHAR(14)
);
