-- =============================================
-- Table: cloud_data_warehouse.generic_table_all
-- Columns: 63
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.generic_table_all (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_src_sys_nm VARCHAR(80),
    meta_iud_flg VARCHAR(1),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    table_number BIGINT NOT NULL,
    gpi VARCHAR(14) NOT NULL,
    maximum_days BIGINT,
    status_code VARCHAR(1),
    mac_drug_code VARCHAR(1),
    ndc_type_code BIGINT,
    ndc VARCHAR(11),
    cross_reference VARCHAR(1),
    copay BIGINT,
    rx_otc_code VARCHAR(1),
    maximum_age BIGINT,
    generic_code VARCHAR(1),
    duration BIGINT,
    duration_kind VARCHAR(1),
    metric_quantity_per_rx NUMERIC(10, 3),
    time_frame BIGINT,
    metric_quantity_per_time NUMERIC(10, 3),
    rx_quantity_per_time BIGINT,
    reject_number BIGINT,
    metric_quantity_per_copay NUMERIC(10, 3),
    copay_per_month_flag VARCHAR(1),
    skip_limit_flag VARCHAR(1),
    generic_table_override_flag VARCHAR(1),
    copay_schedule_type VARCHAR(6),
    mail_mandate_flag VARCHAR(1),
    preferred_message VARCHAR(30),
    gpi_prior_auth_req VARCHAR(14),
    reimbursement_schedule_type VARCHAR(6),
    auto_create_gpi VARCHAR(14),
    minimum_age_limit BIGINT,
    effective_date DATE,
    term_date DATE,
    manufacturer VARCHAR(10),
    female_max_age_years BIGINT,
    female_max_age_months BIGINT,
    female_min_age_years BIGINT,
    female_min_age_months BIGINT,
    male_max_age_years BIGINT,
    male_max_age_months BIGINT,
    male_min_age_years BIGINT,
    male_min_age_months BIGINT,
    gender_max_min_flag VARCHAR(1),
    daw_1_copay_schedule VARCHAR(6),
    days_supply_per_timeframe BIGINT,
    plan_max_mult VARCHAR(1),
    unit_per_day NUMERIC(18, 2),
    post_a_reject BIGINT,
    min_day_supply BIGINT,
    min_qty NUMERIC(18, 3),
    plan_max_benefit NUMERIC(18, 2),
    reimb_sched_nbr BIGINT,
    gen_cd_cov VARCHAR(1),
    max_claim_amt NUMERIC(18, 2),
    add_id VARCHAR(15),
    change_id VARCHAR(15),
    claim_cost_per_time_frame NUMERIC(18, 2)
);
