-- =============================================
-- Table: cloud_data_warehouse.group_data
-- Columns: 351
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.group_data (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_src_sys_nm VARCHAR(80),
    meta_iud_flg VARCHAR(1),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    group_number VARCHAR(20),
    group_name VARCHAR(30),
    alt_group_number VARCHAR(20),
    sponsor_number BIGINT,
    sponsor_name VARCHAR(30),
    system_number BIGINT,
    system_name VARCHAR(30),
    system_link VARCHAR(10),
    group_street VARCHAR(30),
    group_zip VARCHAR(5),
    group_eff_date DATE,
    group_ter_date DATE,
    disp_fee_description VARCHAR(30),
    copay_description VARCHAR(30),
    master_group BIGINT,
    group_benefit_code VARCHAR(16),
    group_master_flag VARCHAR(1),
    group_benefit_description VARCHAR(30),
    odaw_1_tc BIGINT,
    odaw_2_tc BIGINT,
    gen_tc BIGINT,
    np_tc BIGINT,
    single_tc BIGINT,
    brand_tc BIGINT,
    bc_tc BIGINT,
    copay_number BIGINT,
    plan_key VARCHAR(16),
    sub_group INTEGER,
    formulary_structure VARCHAR(1),
    active_system VARCHAR(1),
    odaw_1_fixed_out NUMERIC(18, 2),
    odaw_1_pct_out NUMERIC(18, 4),
    odaw_2_fixed NUMERIC(18, 2),
    odaw_2_pct NUMERIC(18, 4),
    gen_fixed NUMERIC(18, 2),
    gen_pct NUMERIC(18, 4),
    np_fixed NUMERIC(18, 2),
    np_pct NUMERIC(18, 4),
    single_fixed NUMERIC(18, 2),
    single_pct NUMERIC(18, 4),
    brand_fixed NUMERIC(18, 2),
    brand_pct NUMERIC(18, 4),
    bc_fixed NUMERIC(18, 2),
    bc_pct NUMERIC(18, 4),
    depo_tc BIGINT,
    depo_fixed NUMERIC(18, 2),
    inj_tc BIGINT,
    depo_pct NUMERIC(18, 4),
    inj_fixed NUMERIC(18, 2),
    inj_pct NUMERIC(18, 4),
    split_tc BIGINT,
    split_fixed NUMERIC(18, 2),
    split_pct NUMERIC(18, 4),
    sys_link_description VARCHAR(60),
    comp_tc BIGINT,
    comp_fixed NUMERIC(18, 2),
    comp_pct NUMERIC(18, 4),
    multi_tc BIGINT,
    multi_fixed NUMERIC(18, 2),
    multi_pct NUMERIC(18, 4),
    npbc_tc BIGINT,
    npbc_fixed NUMERIC(18, 2),
    npbc_pct NUMERIC(18, 4),
    np_daw_1_tc BIGINT,
    np_daw_1_fixed NUMERIC(18, 2),
    np_daw_1_pct NUMERIC(18, 4),
    np_daw_2_tc BIGINT,
    np_daw_2_fixed NUMERIC(18, 2),
    np_daw_2_pct NUMERIC(18, 4),
    npm_tc BIGINT,
    npm_fixed NUMERIC(18, 2),
    npm_pct NUMERIC(18, 4),
    npn_tc BIGINT,
    npn_fixed NUMERIC(18, 2),
    npn_pct NUMERIC(18, 4),
    odaw_3_tc BIGINT,
    odaw_3_fixed NUMERIC(18, 2),
    odaw_3_pct NUMERIC(18, 4),
    diff_flag VARCHAR(1),
    diff_table_1 BIGINT,
    diff_eff_1 DATE,
    diff_ter_1 DATE,
    diff_table_2 BIGINT,
    diff_eff_2 DATE,
    diff_ter_2 DATE,
    diff_table_3 BIGINT,
    diff_eff_3 DATE,
    diff_ter_3 DATE,
    sys_street_1 VARCHAR(30),
    sys_street_2 VARCHAR(30),
    sys_city VARCHAR(18),
    sys_state VARCHAR(2),
    sys_zip VARCHAR(5),
    sys_zip_4 VARCHAR(4),
    spo_street_1 VARCHAR(24),
    spo_street_2 VARCHAR(24),
    spo_city VARCHAR(18),
    spo_state VARCHAR(2),
    spo_zip_4 VARCHAR(4),
    spo_no_financial VARCHAR(1),
    spo_mail_retail_flag VARCHAR(1),
    group_city VARCHAR(18),
    group_state VARCHAR(2),
    spo_zip VARCHAR(5),
    acct_type VARCHAR(50),
    system_t_off_cycle VARCHAR(1),
    physician_code_option VARCHAR(1),
    dependent_elig_option VARCHAR(1),
    valid_birth_option VARCHAR(1),
    cardholder_number_flag VARCHAR(1),
    accum_process VARCHAR(1),
    broker VARCHAR(12),
    system_client_type VARCHAR(5),
    sponsor_account_type VARCHAR(10),
    in_patch VARCHAR(1),
    network_1 BIGINT,
    network_effective_1 DATE,
    network_term_1 DATE,
    network_2 BIGINT,
    network_effective_2 DATE,
    network_term_2 DATE,
    network_3 BIGINT,
    network_effective_3 DATE,
    network_term_3 DATE,
    network_4 BIGINT,
    network_effective_4 DATE,
    network_term_4 DATE,
    network_5 BIGINT,
    network_effective_5 DATE,
    network_term_5 DATE,
    network_6 BIGINT,
    network_effective_6 DATE,
    network_term_6 DATE,
    network_7 BIGINT,
    network_effective_7 DATE,
    network_term_7 DATE,
    network_8 BIGINT,
    network_effective_8 DATE,
    network_term_8 DATE,
    network_9 BIGINT,
    network_effective_9 DATE,
    network_term_9 DATE,
    network_10 BIGINT,
    network_effective_10 DATE,
    network_term_10 DATE,
    birth_month_flag VARCHAR(2),
    mail_order_nabp_1 BIGINT,
    mail_order_eff_1 DATE,
    mail_order_nabp_2 BIGINT,
    mail_order_eff_2 DATE,
    mail_order_nabp_3 BIGINT,
    mail_order_eff_3 DATE,
    deduct_copay BIGINT,
    max_copay BIGINT,
    troop_copay BIGINT,
    rollover_date_2 DATE,
    rollover_date_3 DATE,
    rollover_date_4 DATE,
    rollover_date_5 DATE,
    rollover_date_6 DATE,
    rollover_date_7 DATE,
    rollover_date_8 DATE,
    rollover_date_9 DATE,
    rollover_date_10 DATE,
    rollover_date_1 DATE,
    disp_fee_eff_date_1 DATE,
    copay_eff_date_1 DATE,
    copay_number_1 BIGINT,
    copay_number_2 BIGINT,
    plan_eff_date_1 DATE,
    limit_kind_1 VARCHAR(1),
    plan_number_2 VARCHAR(8),
    limit_kind_2 VARCHAR(1),
    plan_name VARCHAR(30),
    limit_months BIGINT,
    limit_member BIGINT,
    group_street_2 VARCHAR(40),
    dependent_eligibility VARCHAR(1),
    deduct_copay_2 BIGINT,
    max_copay_2 BIGINT,
    limit_kind_3 VARCHAR(1),
    deduct_copay_3 BIGINT,
    max_copay_3 BIGINT,
    limit_kind_4 VARCHAR(1),
    deduct_copay_4 BIGINT,
    max_copay_4 BIGINT,
    limit_kind_5 VARCHAR(1),
    deduct_copay_5 BIGINT,
    max_copay_5 BIGINT,
    limit_kind_6 VARCHAR(1),
    deduct_copay_6 BIGINT,
    max_copay_6 BIGINT,
    limit_kind_7 VARCHAR(1),
    deduct_copay_7 BIGINT,
    max_copay_7 BIGINT,
    limit_kind_8 VARCHAR(1),
    deduct_copay_8 BIGINT,
    max_copay_8 BIGINT,
    limit_kind_9 VARCHAR(1),
    deduct_copay_9 BIGINT,
    max_copay_9 BIGINT,
    limit_kind_10 VARCHAR(1),
    deduct_copay_10 BIGINT,
    max_copay_10 BIGINT,
    dependent_age_limt_1 BIGINT,
    college_age_limit_1 BIGINT,
    disability_age_limit_1 BIGINT,
    special_age_limit_1 BIGINT,
    dependent_age_limit_2 BIGINT,
    college_age_limt_2 BIGINT,
    disability_age_limit_2 BIGINT,
    special_age_limit_2 BIGINT,
    dependent_age_limit_3 BIGINT,
    college_age_limit_3 BIGINT,
    disability_age_limit_3 BIGINT,
    special_age_limit_3 BIGINT,
    network_number_90_day BIGINT,
    option_flag_90_day VARCHAR(1),
    sponsor_change VARCHAR(15),
    age_date_cymd_1 DATE,
    age_date_cymd_2 DATE,
    age_date_cymd_3 DATE,
    ao_cymd_1 DATE,
    ao_number_1 BIGINT,
    ao_cymd_2 DATE,
    ao_number_2 BIGINT,
    ao_cymd_3 DATE,
    ao_number_3 BIGINT,
    ao_cymd_4 DATE,
    ao_number_4 BIGINT,
    ao_cymd_5 DATE,
    ao_number_5 BIGINT,
    back_bill_date DATE,
    back_bill_typ_code VARCHAR(1),
    card_flag VARCHAR(8),
    cards_single BIGINT,
    cards_family BIGINT,
    disp_fee_eff_date_2 DATE,
    disp_fee_eff_date_3 DATE,
    disp_schedule_number_1 BIGINT,
    disp_schedule_number_2 BIGINT,
    disp_schedule_number_3 BIGINT,
    drug_detail_flag VARCHAR(1),
    pa_phone VARCHAR(21),
    sub_flag VARCHAR(1),
    troop_copay_2 BIGINT,
    troop_copay_3 BIGINT,
    troop_eff_date_1 DATE,
    troop_eff_date_2 DATE,
    troop_eff_date_3 DATE,
    year_roll_date_1 DATE,
    year_roll_date_2 DATE,
    year_roll_date_3 DATE,
    copay_eff_2 DATE,
    copay_eff_3 DATE,
    copay_eff_4 DATE,
    copay_eff_5 DATE,
    copay_eff_6 DATE,
    copay_eff_7 DATE,
    copay_eff_8 DATE,
    copay_eff_9 DATE,
    copay_eff_10 DATE,
    copay_num_3 BIGINT,
    copay_num_4 BIGINT,
    copay_num_5 BIGINT,
    copay_num_6 BIGINT,
    copay_num_7 BIGINT,
    copay_num_8 BIGINT,
    copay_num_9 BIGINT,
    copay_num_10 BIGINT,
    pos_tip VARCHAR(1),
    ds_term_logic VARCHAR(1),
    adm_eff_date_1 DATE,
    adm_schedule_number_1 BIGINT,
    adm_eff_date_2 DATE,
    adm_schedule_number_2 BIGINT,
    adm_eff_date_3 DATE,
    adm_schedule_number_3 BIGINT,
    adm_eff_date_4 DATE,
    adm_schedule_number_4 BIGINT,
    adm_eff_date_5 DATE,
    adm_schedule_number_5 BIGINT,
    tc_zip_flag VARCHAR(1),
    broker_number_1 VARCHAR(4),
    broker_eff_date_1 DATE,
    broker_number_2 VARCHAR(4),
    broker_eff_date_2 DATE,
    broker_number_3 VARCHAR(4),
    broker_eff_date_3 DATE,
    hospice_flag VARCHAR(1),
    govt_reject VARCHAR(1),
    medical_inb_accum_flag VARCHAR(1),
    optimal_mac_flag VARCHAR(1),
    sponsor_tpa VARCHAR(4),
    ppap_nonguar_fund VARCHAR(1),
    master_group_name VARCHAR(30),
    sc_trans_date DATE,
    zip_4 BIGINT,
    plan_eff_date_2 DATE,
    plan_eff_date_3 DATE,
    plan_number_3 VARCHAR(8),
    plan_eff_date_4 DATE,
    plan_number_4 VARCHAR(8),
    plan_eff_date_5 DATE,
    plan_number_5 VARCHAR(8),
    plan_eff_date_6 DATE,
    plan_number_6 VARCHAR(8),
    plan_eff_date_7 DATE,
    plan_number_7 VARCHAR(8),
    plan_eff_date_8 DATE,
    plan_number_8 VARCHAR(8),
    plan_eff_date_9 DATE,
    plan_number_9 VARCHAR(8),
    plan_eff_date_10 DATE,
    plan_number_10 VARCHAR(8),
    rollover_date_11 DATE,
    rollover_date_12 DATE,
    rollover_date_13 DATE,
    rollover_date_14 DATE,
    rollover_date_15 DATE,
    rollover_date_16 DATE,
    rollover_date_17 DATE,
    rollover_date_18 DATE,
    benefit_code_2 VARCHAR(16),
    benefit_code_3 VARCHAR(16),
    benefit_code_4 VARCHAR(16),
    benefit_code_5 VARCHAR(16),
    cob_fee_flag VARCHAR(1),
    flag_340b VARCHAR(1),
    plan_number_1 VARCHAR(8),
    entry_date DATE,
    change_date DATE,
    last_name_check VARCHAR(1),
    add_id VARCHAR(15),
    change_id VARCHAR(15),
    max_single NUMERIC(18, 2),
    max_family NUMERIC(18, 2),
    deduct_single NUMERIC(18, 2),
    deduct_family NUMERIC(18, 2),
    formulary BIGINT,
    period_ending_date DATE,
    state_comp_source VARCHAR(1),
    reject_260_flag VARCHAR(1),
    grp_to_grp_x_walk VARCHAR(1)
);
