-- =============================================
-- Table: cloud_data_warehouse.inlog_20250728
-- Columns: 76
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.inlog_20250728 (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_src_sys_nm VARCHAR(80),
    meta_iud_flg VARCHAR(1),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    inl_system_nbr BIGINT,
    inl_sponsor_nbr BIGINT,
    inl_group_nbr VARCHAR(20),
    inl_period_ending DATE,
    inl_alt_group_nbr VARCHAR(20),
    inl_group_name VARCHAR(30),
    inl_sys_claim_inv_num BIGINT,
    inl_spo_claim_inv_num BIGINT,
    inl_grp_claim_inv_num BIGINT,
    inl_claim_count BIGINT,
    inl_claim_inv_amt NUMERIC(18, 2),
    inl_copay NUMERIC(18, 2),
    inl_disp_fee NUMERIC(18, 2),
    inl_ing_cost NUMERIC(18, 2),
    inl_tax NUMERIC(18, 2),
    inl_diff_admin NUMERIC(18, 2),
    inl_sys_admin_fee NUMERIC(18, 2),
    inl_spo_admin_fee NUMERIC(18, 2),
    inl_grp_admin_fee NUMERIC(18, 2),
    inl_sys_admin_inv_num BIGINT,
    inl_spo_admin_inv_num BIGINT,
    inl_grp_admin_inv_num BIGINT,
    inl_claim_paid_flag VARCHAR(1),
    inl_admin_paid_flag VARCHAR(1),
    inl_claim_paid_date DATE,
    inl_admin_paid_date DATE,
    inl_check_charge NUMERIC(18, 2),
    inl_mkt_charge NUMERIC(18, 2),
    inl_number_of_checks BIGINT,
    inl_special_period_ending DATE,
    inl_ta_amt NUMERIC(18, 2),
    inl_rented_network_claims BIGINT,
    inl_rented_network_amount NUMERIC(18, 2),
    inl_claim_chk_rec_date DATE,
    inl_claim_chk_ref_num VARCHAR(20),
    inl_claim_chk_ref_amt NUMERIC(18, 2),
    inl_admin_chk_rec_date DATE,
    inl_admin_chk_ref_num VARCHAR(20),
    inl_admin_chk_ref_amt NUMERIC(18, 2),
    inl_admin_fee NUMERIC(18, 2),
    inl_sys_card_fee NUMERIC(18, 2),
    inl_spo_card_fee NUMERIC(18, 2),
    inl_grp_card_fee NUMERIC(18, 2),
    inl_sys_card_inv BIGINT,
    inl_spo_card_inv BIGINT,
    inl_grp_card_inv BIGINT,
    inl_num_of_cards BIGINT,
    inl_client_discount_fee NUMERIC(18, 2),
    inl_pdm_discount_fee NUMERIC(18, 2),
    inl_broker_claim_count BIGINT,
    inl_broker_amt_sys NUMERIC(18, 2),
    inl_broker_amt_spo NUMERIC(18, 2),
    inl_broker_amt_grp NUMERIC(18, 2),
    inl_med_sub_claim_count BIGINT,
    eps_claim_count BIGINT,
    eps_sys_admin_amount NUMERIC(18, 2),
    eps_spo_admin_amount NUMERIC(18, 2),
    eps_grp_admin_amount NUMERIC(18, 2),
    eps_claim_amount NUMERIC(18, 2),
    serv_fee_claim_count BIGINT,
    serv_fee_sys_admin_amount NUMERIC(18, 2),
    serv_fee_spo_admin_amount NUMERIC(18, 2),
    serv_fee_grp_admin_amount NUMERIC(18, 2),
    serv_fee_claim_amount NUMERIC(18, 2),
    no_fin_claim_count BIGINT,
    no_fin_sys_admin_amount NUMERIC(18, 2),
    no_fin_spo_admin_amount NUMERIC(18, 2),
    no_fin_grp_admin_amount NUMERIC(18, 2),
    no_fin_claim_amount NUMERIC(18, 2)
);
