-- =============================================
-- Table: cloud_data_warehouse.limit_daily
-- Columns: 109
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.limit_daily (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_src_sys_nm VARCHAR(80),
    meta_iud_flg VARCHAR(1),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    system_nbr INTEGER,
    sponsor_nbr INTEGER,
    group_nbr INTEGER,
    cardholder_nbr VARCHAR(10),
    member_nbr VARCHAR(2),
    bin INTEGER,
    roll_up_code VARCHAR(20),
    roll_date TIMESTAMP,
    extract_date TIMESTAMP,
    claims INTEGER,
    t_ing_bil NUMERIC(18, 2),
    t_copay NUMERIC(18, 2),
    t_disp NUMERIC(18, 2),
    t_tax NUMERIC(18, 2),
    t_ing_paid NUMERIC(18, 2),
    rx_1 INTEGER,
    rx_date_1 TIMESTAMP,
    ing_bil1 NUMERIC(18, 2),
    copay_1 NUMERIC(18, 2),
    disp_1 NUMERIC(18, 2),
    tax_1 NUMERIC(18, 2),
    ing_paid_1 NUMERIC(18, 2),
    rej_1 INTEGER,
    rx_2 INTEGER,
    rx_date_2 TIMESTAMP,
    ing_bil_2 NUMERIC(18, 2),
    copay_2 NUMERIC(18, 2),
    disp_2 NUMERIC(18, 2),
    tax_2 NUMERIC(18, 2),
    ing_paid_2 NUMERIC(18, 2),
    rej_2 INTEGER,
    rx_3 INTEGER,
    rx_date_3 TIMESTAMP,
    ing_bil_3 NUMERIC(18, 2),
    copay_3 NUMERIC(18, 2),
    disp_3 NUMERIC(18, 2),
    tax_3 NUMERIC(18, 2),
    ing_paid_3 NUMERIC(18, 2),
    rej_3 INTEGER,
    met_date TIMESTAMP,
    last_qtr_carry_over NUMERIC(18, 2),
    deduct_flag VARCHAR(1),
    deduct_date TIMESTAMP,
    stop_flag VARCHAR(1),
    stop_date TIMESTAMP,
    medical_deduct NUMERIC(18, 2),
    med_out_of_pocket NUMERIC(18, 2),
    met_date_max TIMESTAMP,
    half_letter TIMESTAMP,
    eob_letter TIMESTAMP,
    sponsor_carry_over INTEGER,
    add_to_max NUMERIC(18, 2),
    recalc_date_1 TIMESTAMP,
    recalc_code_1 INTEGER,
    recalc_date_2 TIMESTAMP,
    recalc_code_2 INTEGER,
    recalc_date_3 TIMESTAMP,
    recalc_code_3 INTEGER,
    dont_recalc_flag VARCHAR(1),
    m_claims INTEGER,
    m_ing_bil NUMERIC(18, 2),
    m_copay NUMERIC(18, 2),
    m_disp NUMERIC(18, 2),
    m_tax NUMERIC(18, 2),
    m_ing_paid NUMERIC(18, 2),
    met_date_deduct_mail TIMESTAMP,
    last_qtr_carry_over_mail NUMERIC(18, 2),
    met_date_max_mail TIMESTAMP,
    add_to_max_mail NUMERIC(18, 2),
    letter_code VARCHAR(10),
    deduct_amt_only NUMERIC(18, 2),
    ta_begin_bal NUMERIC(18, 2),
    ta_lcd INTEGER,
    ta_run_bal NUMERIC(18, 2),
    retail_penalty_amt NUMERIC(18, 2),
    mail_penalty_amt NUMERIC(18, 2),
    troop_amt NUMERIC(18, 2),
    add_to_troop NUMERIC(18, 2),
    tot_drug_2250 NUMERIC(18, 2),
    tot_drug_5100 NUMERIC(18, 2),
    stand_deduct_only NUMERIC(18, 2),
    med_add_to_deduct NUMERIC(18, 2),
    med_add_to_amt_paid NUMERIC(18, 2),
    add_to_single_max NUMERIC(18, 2),
    add_to_family_max NUMERIC(18, 2),
    add_to_life_max NUMERIC(18, 2),
    add_to_troop_fir NUMERIC(18, 2),
    add_to_tds_fir NUMERIC(18, 2),
    last_fir_date TIMESTAMP,
    add_to_deduct_fir NUMERIC(18, 2),
    rest_k_limit VARCHAR(1),
    carry_forward_oop NUMERIC(18, 2),
    carry_forward_ded NUMERIC(18, 2),
    pdm_add_to_ded NUMERIC(18, 2),
    pdm_add_to_oop NUMERIC(18, 2),
    add_id VARCHAR(15),
    change_id VARCHAR(15),
    diff_ing_cost_paid NUMERIC(18, 2),
    diff_disp_fee NUMERIC(18, 2),
    limit_mbr_max NUMERIC(18, 2),
    add_date TIMESTAMP,
    change_date TIMESTAMP
);
