-- =============================================
-- Table: cloud_data_warehouse.overrides
-- Columns: 49
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.overrides (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_src_sys_nm VARCHAR(80),
    meta_iud_flg VARCHAR(1),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    cardholder_number VARCHAR(10) NOT NULL,
    member_number VARCHAR(2) NOT NULL,
    sponsor BIGINT NOT NULL,
    gpi VARCHAR(14) NOT NULL,
    type_code BIGINT NOT NULL,
    effective_date DATE NOT NULL,
    cardholder_key VARCHAR(20),
    termination_date DATE,
    pharmacy_number BIGINT,
    chain_number BIGINT,
    physician_number VARCHAR(10),
    days_supply BIGINT,
    metric_quantity NUMERIC(18, 3),
    ndc VARCHAR(11),
    copay_schedule BIGINT,
    reason VARCHAR(60),
    max_claim_amount NUMERIC(18, 2),
    copay_fix NUMERIC(18, 2),
    copay_percentage NUMERIC(18, 2),
    pay_pharm_billed BIGINT,
    rx_per_time_frame BIGINT,
    invalid_birth_date DATE,
    pay_pharm_cap NUMERIC(18, 2),
    create_flag VARCHAR(1),
    dispensing_fee NUMERIC(18, 2),
    copay_schedule_type_new VARCHAR(6),
    copay_schedule_type_old VARCHAR(6),
    refill_number BIGINT,
    prior_authorization BIGINT,
    reason_code BIGINT,
    record_type VARCHAR(1),
    user VARCHAR(12),
    occurrence BIGINT,
    generic_incentive_flag VARCHAR(1),
    refill_prcnt NUMERIC(18, 2),
    plan_max NUMERIC(18, 2),
    post_a_reject BIGINT,
    unit_per_day NUMERIC(18, 2),
    skip_limit_flag VARCHAR(1),
    enter_date DATE,
    change_date DATE,
    ov_maximizer_percent NUMERIC(18, 4)
);
