-- =============================================
-- Table: cloud_data_warehouse.pdmi_config_master
-- Columns: 59
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.pdmi_config_master (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    meta_iud_flg VARCHAR(10),
    meta_src_sys_nm VARCHAR(10),
    t_link VARCHAR(5),
    system_spon_grp VARCHAR(28),
    system_nbr INTEGER,
    sponsor_nbr INTEGER,
    group_nbr FLOAT8,
    rec_type VARCHAR(3),
    date_type VARCHAR(2),
    data_type VARCHAR(3),
    data VARCHAR(26),
    amt_type VARCHAR(3),
    occ INTEGER,
    min_amt NUMERIC(18, 4),
    max_amt NUMERIC(18, 4),
    mq_min_amt NUMERIC(18, 3),
    mq_max_amt NUMERIC(18, 3),
    ds_min_amt BIGINT,
    ds_max_amt BIGINT,
    seq_nbr INTEGER,
    eff_date TIMESTAMP,
    term_date TIMESTAMP,
    brand_id VARCHAR(20),
    disp_fee NUMERIC(18, 2),
    cms_excl_date TIMESTAMP,
    cms_last_name VARCHAR(35),
    cms_first_name VARCHAR(25),
    cms_middle_name VARCHAR(25),
    cms_bus_name VARCHAR(70),
    cms_general VARCHAR(50),
    cms_specialty VARCHAR(150),
    cms_ein VARCHAR(9),
    cms_dob VARCHAR(8),
    cms_address_1 VARCHAR(55),
    cms_address_2 VARCHAR(55),
    cms_city VARCHAR(40),
    cms_state VARCHAR(2),
    cms_zip VARCHAR(5),
    cms_last_update_date TIMESTAMP,
    rej_code INTEGER,
    compu_msg VARCHAR(39),
    compu_additional VARCHAR(200),
    ds_min_amt_rec_type_006 NUMERIC(18, 4),
    ds_max_amt_rec_type_006 NUMERIC(18, 4),
    mq_min_amt_rec_type_006 NUMERIC(18, 4),
    mq_max_amt_rec_type_006 NUMERIC(18, 4),
    service_fee NUMERIC(18, 2),
    copay_table INTEGER,
    plan_number VARCHAR(8),
    copay_amt NUMERIC(18, 4),
    add_id VARCHAR(15),
    change_id VARCHAR(15),
    add_date TIMESTAMP,
    change_date TIMESTAMP
);
