-- =============================================
-- Table: cloud_data_warehouse.recordstoupdaterv601
-- Columns: 349
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.recordstoupdaterv601 (
    meta_surr_key VARCHAR(80),
    meta_hash_key VARCHAR(80),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind CHAR(1),
    claim_key CHAR(14) NOT NULL,
    batch_number CHAR(8),
    claim_number INTEGER,
    claim_type INTEGER,
    payment_dir INTEGER,
    cardholder_number CHAR(10),
    member_number CHAR(2),
    pharmacy_number INTEGER,
    network_key CHAR(16),
    chain_number INTEGER,
    reject_code_1 INTEGER,
    reject_code_2 INTEGER,
    process_date DATE,
    rx_number BIGINT,
    rx_date DATE,
    rx_time TIMESTAMP,
    new_refill CHAR(1),
    generic_code CHAR(1),
    drug_pref_ind CHAR(2),
    metric_quantity NUMERIC(18, 3),
    days_supply INTEGER,
    ing_billed NUMERIC(18, 2),
    ing_paid NUMERIC(18, 2),
    disp_fee NUMERIC(18, 2),
    copay NUMERIC(18, 2),
    tax NUMERIC(18, 2),
    admin_fee NUMERIC(18, 2),
    amount_paid NUMERIC(18, 2),
    ucr_amount NUMERIC(18, 2),
    awp_processed NUMERIC(18, 5),
    generic_savings NUMERIC(18, 2),
    member_birth DATE,
    sex CHAR(1),
    cardholder_key CHAR(20),
    physician_key CHAR(14),
    diagnosis_code CHAR(6),
    group_number BIGINT,
    drug_key CHAR(15),
    gpi CHAR(14),
    ndc_type_code INTEGER,
    ndc NUMERIC(11, 0),
    main_drug CHAR(1),
    benefit_key CHAR(24),
    copay_key CHAR(12),
    copay_table INTEGER,
    dispense_table INTEGER,
    plan_key CHAR(12),
    plan_number CHAR(4),
    mac_number INTEGER,
    daw_indicator CHAR(1),
    compound_code INTEGER,
    third_party_code CHAR(1),
    rx_otc CHAR(1),
    adjustment_code_2 INTEGER,
    generic_table INTEGER,
    reimb_rate_table INTEGER,
    mail_order_flag CHAR(1),
    line_number INTEGER,
    claims_counter INTEGER,
    current_claim_indicator CHAR(1),
    period_ending DATE,
    paid_date DATE,
    price_indicator CHAR(1),
    adjustment_code INTEGER,
    network_number INTEGER,
    step_therapy_number INTEGER,
    pcp_number CHAR(14),
    date_key CHAR(14),
    exception_01 INTEGER,
    override_1 INTEGER,
    rel_code CHAR(2),
    skip_limit_flag INTEGER,
    exception_02 INTEGER,
    exception_03 INTEGER,
    exception_04 INTEGER,
    exception_05 INTEGER,
    exception_06 INTEGER,
    exception_07 INTEGER,
    exception_08 INTEGER,
    exception_09 INTEGER,
    exception_10 INTEGER,
    exception_11 INTEGER,
    exception_12 INTEGER,
    exception_13 INTEGER,
    exception_14 INTEGER,
    exception_15 INTEGER,
    exception_16 INTEGER,
    exception_17 INTEGER,
    exception_18 INTEGER,
    exception_19 INTEGER,
    exception_20 INTEGER,
    override_2 INTEGER,
    override_3 INTEGER,
    override_4 INTEGER,
    override_5 INTEGER,
    override_6 INTEGER,
    override_7 INTEGER,
    override_8 INTEGER,
    override_9 INTEGER,
    override_10 INTEGER,
    form_gt INTEGER,
    maint_gt INTEGER,
    physician_key_2 CHAR(18),
    adj_code_1 INTEGER,
    adj_code_info INTEGER,
    coverage_type CHAR(1),
    orig_rx_date CHAR(8),
    refills_auth INTEGER,
    refill_count_num INTEGER,
    reversal_code INTEGER,
    sys_number INTEGER,
    sponsor_number INTEGER,
    upd_code INTEGER,
    pho_number CHAR(14),
    claim_cnty CHAR(2),
    member_first_name CHAR(15),
    member_middle_initial CHAR(1),
    member_last_name CHAR(20),
    version_number CHAR(1),
    awp_100_percent NUMERIC(18, 2),
    diff_ing_paid NUMERIC(18, 2),
    diff_disp_fee NUMERIC(18, 2),
    diff_table_number INTEGER,
    mac_reference_price NUMERIC(18, 2),
    contract_rate_price NUMERIC(18, 2),
    order_number CHAR(20),
    dispensing_status CHAR(1),
    assoc_rx_date DATE,
    assoc_rx_number BIGINT,
    intended_days_supply INTEGER,
    partial_ing_cost_paid NUMERIC(18, 2),
    intended_met_qty NUMERIC(18, 3),
    ta_amount NUMERIC(18, 2),
    other_coverage_code INTEGER,
    other_payor_amount NUMERIC(18, 2),
    date_of_injury DATE,
    indep_code INTEGER,
    penalty_amount NUMERIC(18, 2),
    patient_last_name CHAR(20),
    patient_middle_initial CHAR(1),
    patient_first_name CHAR(15),
    sub_clarification_code_1 INTEGER,
    sub_clarification_code_2 INTEGER,
    sub_clarification_code_3 INTEGER,
    pa_mc_code_and_number NUMERIC(12, 0),
    level_of_service INTEGER,
    max_amt NUMERIC(18, 2),
    deduct_amt NUMERIC(18, 2),
    dmr_nabp INTEGER,
    other_payer_order INTEGER,
    nonlics_deduct_amt NUMERIC(18, 2),
    standard_deduct_amt NUMERIC(18, 2),
    special_deduct_amt NUMERIC(18, 2),
    team_member CHAR(4),
    npi_number CHAR(10),
    card_seq_number INTEGER,
    add_to_troop NUMERIC(10, 2),
    pcn CHAR(10),
    bin_number INTEGER,
    eft_payment CHAR(1),
    medd_gap_discount NUMERIC(18, 2),
    medd_beg_phase CHAR(1),
    medd_end_phase CHAR(1),
    rxnumber_length INTEGER,
    patient_paid_amount NUMERIC(18, 2),
    sub_clarification_count INTEGER,
    other_payer_bin INTEGER,
    trans_ref_number CHAR(10),
    other_payer_pcn CHAR(14),
    other_payer_group CHAR(14),
    soj CHAR(2),
    other_payer_cardholder CHAR(20),
    compound_dosage_description_code CHAR(2),
    compound_dispensing_id CHAR(1),
    compound_count INTEGER,
    amt_applied_period_deduct NUMERIC(18, 2),
    amt_exceed_period_benefit NUMERIC(18, 2),
    amt_copay NUMERIC(18, 2),
    amt_coinsurance NUMERIC(18, 2),
    amt_attr_processor_fee NUMERIC(18, 2),
    amt_attr_sales_tax NUMERIC(18, 2),
    amt_attr_provider_net_select NUMERIC(18, 2),
    amt_attr_prod_sel_brand NUMERIC(18, 2),
    amt_attr_prod_sel_non_pf NUMERIC(18, 2),
    amt_attr_prod_sel_brd_non_pf NUMERIC(18, 2),
    health_plan_funded_assist_amt NUMERIC(18, 2),
    gross_amount_due NUMERIC(18, 2),
    incentive_amount_sub NUMERIC(18, 2),
    dispensing_fee_sub NUMERIC(18, 2),
    other_amount_claimed_sub NUMERIC(18, 2),
    flat_sales_tax_amount_sub NUMERIC(18, 2),
    pct_sales_tax_amount_sub NUMERIC(18, 2),
    pct_sales_tax_rate_sub NUMERIC(18, 4),
    medicaid_subrogation CHAR(20),
    medicaid_paid_amt NUMERIC(18, 2),
    pharmacy_service_type INTEGER,
    pharmacist_license VARCHAR(50),
    sequence_number VARCHAR(256),
    uid VARCHAR(36),
    nabp_7 VARCHAR(7),
    preferred_status CHAR(1),
    rx_origin_code INTEGER,
    customer_location INTEGER,
    eligibility_clarification_code INTEGER,
    primary_prescriber CHAR(10),
    basis_of_cost_determination CHAR(2),
    document_number INTEGER,
    processor_control_flag CHAR(1),
    dmr_reimbursement_payment_type INTEGER,
    pharmacy_option CHAR(1),
    pharmacy_name CHAR(30),
    product_description_abbreviation CHAR(25),
    alt_cardholder_number CHAR(13),
    alt_group_number CHAR(12),
    thera_class INTEGER,
    rx_otc_class CHAR(1),
    batch_date DATE,
    benefit_code CHAR(16),
    claim_indicator CHAR(1),
    rx_date_julian INTEGER,
    batch_date_julian INTEGER,
    county CHAR(2),
    seq_number VARCHAR(20),
    physician_number_x VARCHAR(50),
    cms_part_d_facility VARCHAR(1),
    approved_msg_code VARCHAR(3),
    time_hhmm VARCHAR(4),
    restack_batch VARCHAR(8),
    restack_claim INTEGER,
    variable_mac_factor_rate NUMERIC(18, 5),
    patient_residency VARCHAR(2),
    special_packaging_ind VARCHAR(1),
    prof_service_code_1 VARCHAR(2),
    prof_service_code_2 VARCHAR(2),
    prof_service_code_3 VARCHAR(2),
    dur_pps_lvl_of_effort VARCHAR(2),
    troop_amt NUMERIC(18, 2),
    redemption_count INTEGER,
    date_of_reversal DATE,
    packaging_indicator VARCHAR(1),
    no_financial_flag VARCHAR(1),
    claim_type_alpha VARCHAR(2),
    ltc_indicator VARCHAR(1),
    dur_lvl_of_effort_1 VARCHAR(2),
    dur_reason_service_1 VARCHAR(2),
    dur_prof_service_code_1 VARCHAR(2),
    dur_result_of_serv_cd_1 VARCHAR(2),
    dur_lvl_of_effort_2 VARCHAR(2),
    dur_reason_service_2 VARCHAR(2),
    dur_prof_service_code_2 VARCHAR(2),
    dur_result_of_serv_cd_2 VARCHAR(2),
    dur_lvl_of_effort_3 VARCHAR(2),
    dur_reason_service_3 VARCHAR(2),
    dur_prof_service_code_3 VARCHAR(2),
    dur_result_of_serv_cd_3 VARCHAR(2),
    dur_lvl_of_effort_4 VARCHAR(2),
    dur_reason_service_4 VARCHAR(2),
    dur_prof_service_code_4 VARCHAR(2),
    dur_result_of_serv_cd_4 VARCHAR(2),
    dur_lvl_of_effort_5 VARCHAR(2),
    dur_reason_service_5 VARCHAR(2),
    dur_prof_service_code_5 VARCHAR(2),
    dur_result_of_serv_cd_5 VARCHAR(2),
    dur_lvl_of_effort_6 VARCHAR(2),
    dur_reason_service_6 VARCHAR(2),
    dur_prof_service_code_6 VARCHAR(2),
    dur_result_of_serv_cd_6 VARCHAR(2),
    dur_lvl_of_effort_7 VARCHAR(2),
    dur_reason_service_7 VARCHAR(2),
    dur_prof_service_code_7 VARCHAR(2),
    dur_result_of_serv_cd_7 VARCHAR(2),
    dur_lvl_of_effort_8 VARCHAR(2),
    dur_reason_service_8 VARCHAR(2),
    dur_prof_service_code_8 VARCHAR(2),
    dur_result_of_serv_cd_8 VARCHAR(2),
    dur_lvl_of_effort_9 VARCHAR(2),
    dur_reason_service_9 VARCHAR(2),
    dur_prof_service_code_9 VARCHAR(2),
    dur_result_of_serv_cd_9 VARCHAR(2),
    scd_claim VARCHAR(1),
    thresh_5100 NUMERIC(18, 2),
    c_formulary_id_flag VARCHAR(1),
    brand_config_occur INTEGER,
    card_id_sent_from_pharm VARCHAR(20),
    hms_physician_id VARCHAR(10),
    tier VARCHAR(1),
    claim_adjudication_time VARCHAR(26),
    age INTEGER,
    quantity_dispensed NUMERIC(18, 3),
    previous_restack_batch VARCHAR(8),
    previous_restack_claim INTEGER,
    wac_ref_price NUMERIC(18, 2),
    specialty_flag VARCHAR(1),
    mail_order_indication VARCHAR(4),
    spcl_patient_disp_fee NUMERIC(18, 2),
    hms_poid VARCHAR(10),
    orig_rev_batch VARCHAR(8),
    orig_rev_claim INTEGER,
    grp_broker_nbr VARCHAR(4),
    payment_center_id VARCHAR(6),
    remit_reconciliation_id VARCHAR(6),
    pdmi_reject_code_1 VARCHAR(4),
    pdmi_reject_code_2 VARCHAR(4),
    pdmi_reject_code_3 VARCHAR(4),
    pdmi_reject_code_4 VARCHAR(4),
    pdmi_reject_code_5 VARCHAR(4),
    pdmi_reject_code_6 VARCHAR(4),
    pdmi_reject_code_7 VARCHAR(4),
    pdmi_reject_code_8 VARCHAR(4),
    pdmi_reject_code_9 VARCHAR(4),
    pdmi_reject_code_10 VARCHAR(4),
    pdmi_reject_code_11 VARCHAR(4),
    pdmi_reject_code_12 VARCHAR(4),
    pdmi_reject_code_13 VARCHAR(4),
    pdmi_reject_code_14 VARCHAR(4),
    pdmi_reject_code_15 VARCHAR(4),
    pdmi_reject_code_16 VARCHAR(4),
    pdmi_reject_code_17 VARCHAR(4),
    pdmi_reject_code_18 VARCHAR(4),
    pdmi_reject_code_19 VARCHAR(4),
    pdmi_reject_code_20 VARCHAR(4),
    amount_applied_to_oop NUMERIC(18, 2),
    n1_claim_key VARCHAR(14),
    n1_batch_number VARCHAR(8),
    n1_claim_number INTEGER,
    user_id VARCHAR(15),
    opioid_factor NUMERIC(18, 2),
    contract_chain_number INTEGER,
    differential_claim_type VARCHAR(6),
    carrier_id VARCHAR(10),
    pharm_electronic_fee NUMERIC(18, 2),
    vaccine_admin_fee NUMERIC(18, 2),
    prescriber_id_qualifier VARCHAR(10),
    ctree_toggle VARCHAR(1),
    orig_med_gen_code VARCHAR(1),
    oth_pay_covg_type VARCHAR(2),
    script_care_claim VARCHAR(1),
    script_care_net_pricing VARCHAR(1),
    quantity_prescribed NUMERIC(18, 3),
    pdmi_admin_fee NUMERIC(18, 2),
    client_sys_spo_admin_fee NUMERIC(18, 2),
    client_spo_grp_admin_fee NUMERIC(18, 2),
    claim_category VARCHAR(12),
    needs_updated BOOLEAN DEFAULT false
);
