-- =============================================
-- Table: cloud_data_warehouse.reimbrateext
-- Columns: 51
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.reimbrateext (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_src_sys_nm VARCHAR(80),
    meta_iud_flg VARCHAR(1),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    reimb_rate_number INTEGER NOT NULL,
    gen_type VARCHAR(6) NOT NULL,
    reimb_rate_descr VARCHAR(50),
    reimb_rate_descr_code BIGINT,
    awp_percent NUMERIC(18, 4),
    fee NUMERIC(18, 2),
    mac_table INTEGER,
    mac_fee NUMERIC(18, 2),
    flat_fee NUMERIC(18, 2),
    cap_amt NUMERIC(18, 2),
    per_month VARCHAR(1),
    active VARCHAR(1),
    otc_fee NUMERIC(18, 2),
    pay_as_contract_rate VARCHAR(1),
    mark_percent NUMERIC(18, 4),
    mark_disp_fee NUMERIC(18, 2),
    plus_diff_table_1 INTEGER,
    plus_diff_table_eff_date_1 TIMESTAMP,
    plus_diff_table_2 INTEGER,
    plus_diff_table_eff_date_2 TIMESTAMP,
    plus_diff_table_3 INTEGER,
    plus_diff_table_eff_date_3 TIMESTAMP,
    pdm_mac_flag VARCHAR(1),
    min_reimb_amt NUMERIC(18, 2),
    elect_fee NUMERIC(18, 2),
    inc_fee NUMERIC(18, 2),
    discount_net_fee NUMERIC(18, 2),
    mac_awp_percent NUMERIC(18, 4),
    mac_awp_number INTEGER,
    awp_factor NUMERIC(18, 4),
    mac_factor_table INTEGER,
    cap_340b NUMERIC(18, 2),
    eft_fee NUMERIC(18, 2),
    wac_fee NUMERIC(18, 2),
    wac_percent NUMERIC(18, 4),
    disp_fee_340b NUMERIC(18, 2),
    reimb_fix_amt NUMERIC(18, 2),
    reimb_cap_amt NUMERIC(18, 2),
    add_id VARCHAR(15),
    change_id VARCHAR(15),
    add_date TIMESTAMP,
    change_date TIMESTAMP,
    ext_date TIMESTAMP,
    add_on_percent NUMERIC(18, 4)
);
