-- =============================================
-- Table: cloud_data_warehouse.reimb_rate_data
-- Columns: 173
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.reimb_rate_data (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_src_sys_nm VARCHAR(80),
    meta_iud_flg VARCHAR(1),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    reimb_rate_number INTEGER,
    reimb_desc CHAR(50),
    o_gen_code CHAR(6),
    o_reim_desc_type FLOAT8,
    o_awp_pcnt NUMERIC(18, 4),
    o_disp_fee NUMERIC(18, 2),
    o_mac_tbl INTEGER,
    o_mac_fee NUMERIC(18, 2),
    o_flat_fee NUMERIC(18, 2),
    o_cap_amt NUMERIC(18, 2),
    o_per_month VARCHAR(1),
    o_active VARCHAR(1),
    o_otc_fee NUMERIC(18, 2),
    o_pay_as_contract_rate VARCHAR(1),
    o_marketing_percentage NUMERIC(18, 4),
    o_marketing_disp_fee NUMERIC(18, 2),
    o_plus_diff_table_1 INTEGER,
    o_plus_diff_table_eff_1 TIMESTAMP,
    o_plus_diff_table_2 INTEGER,
    o_plus_diff_table_eff_2 TIMESTAMP,
    o_plus_diff_table_3 INTEGER,
    o_plus_diff_table_eff_3 TIMESTAMP,
    o_pdm_mac_flag VARCHAR(1),
    o_min_reimb_amt NUMERIC(18, 2),
    o_electronic_fee NUMERIC(18, 2),
    o_incentive_fee NUMERIC(18, 2),
    o_disc_net_fee NUMERIC(18, 2),
    o_mac_awp_prcnt NUMERIC(18, 4),
    o_mac_awp_num INTEGER,
    o_awp_litigation_factor NUMERIC(18, 4),
    o_mac_factor_table INTEGER,
    o_340b_cap NUMERIC(18, 2),
    o_eft_fee NUMERIC(18, 2),
    o_wac_fee NUMERIC(18, 2),
    o_wac_prcnt NUMERIC(18, 4),
    o_340b_disp_fee NUMERIC(18, 2),
    o_reimb_fixed_amt NUMERIC(18, 2),
    o_reimb_cap_amt NUMERIC(18, 2),
    o_add_id VARCHAR(15),
    o_change_id VARCHAR(15),
    o_add_date TIMESTAMP,
    o_chg_date TIMESTAMP,
    m_gen_code CHAR(6),
    m_reim_desc_type FLOAT8,
    m_awp_pcnt NUMERIC(18, 4),
    m_disp_fee NUMERIC(18, 2),
    m_mac_tbl INTEGER,
    m_mac_fee NUMERIC(18, 2),
    m_flat_fee NUMERIC(18, 2),
    m_cap_amt NUMERIC(18, 2),
    m_per_month VARCHAR(1),
    m_active VARCHAR(1),
    m_otc_fee NUMERIC(18, 2),
    m_pay_as_contract_rate VARCHAR(1),
    m_marketing_percentage NUMERIC(18, 4),
    m_marketing_disp_fee NUMERIC(18, 2),
    m_plus_diff_table_1 INTEGER,
    m_plus_diff_table_eff_1 TIMESTAMP,
    m_plus_diff_table_2 INTEGER,
    m_plus_diff_table_eff_2 TIMESTAMP,
    m_plus_diff_table_3 INTEGER,
    m_plus_diff_table_eff_3 TIMESTAMP,
    m_pdm_mac_flag VARCHAR(1),
    m_min_reimb_amt NUMERIC(18, 2),
    m_electronic_fee NUMERIC(18, 2),
    m_incentive_fee NUMERIC(18, 2),
    m_disc_net_fee NUMERIC(18, 2),
    m_mac_awp_prcnt NUMERIC(18, 4),
    m_mac_awp_num INTEGER,
    m_awp_litigation_factor NUMERIC(18, 4),
    m_mac_factor_table INTEGER,
    m_340b_cap NUMERIC(18, 2),
    m_eft_fee NUMERIC(18, 2),
    m_wac_fee NUMERIC(18, 2),
    m_wac_prcnt NUMERIC(18, 4),
    m_340b_disp_fee NUMERIC(18, 2),
    m_reimb_fixed_amt NUMERIC(18, 2),
    m_reimb_cap_amt NUMERIC(18, 2),
    m_add_id VARCHAR(15),
    m_change_id VARCHAR(15),
    m_add_date TIMESTAMP,
    m_chg_date TIMESTAMP,
    n_gen_code VARCHAR(6),
    n_reim_desc_type FLOAT8,
    n_awp_pcnt NUMERIC(18, 4),
    n_disp_fee NUMERIC(18, 2),
    n_mac_tbl INTEGER,
    n_mac_fee NUMERIC(18, 2),
    n_flat_fee NUMERIC(18, 2),
    n_cap_amt NUMERIC(18, 2),
    n_per_month VARCHAR(1),
    n_active VARCHAR(1),
    n_otc_fee NUMERIC(18, 2),
    n_pay_as_contract_rate VARCHAR(1),
    n_marketing_percentage NUMERIC(18, 4),
    n_marketing_disp_fee NUMERIC(18, 2),
    n_plus_diff_table_1 INTEGER,
    n_plus_diff_table_eff_1 TIMESTAMP,
    n_plus_diff_table_2 INTEGER,
    n_plus_diff_table_eff_2 TIMESTAMP,
    n_plus_diff_table_3 INTEGER,
    n_plus_diff_table_eff_3 TIMESTAMP,
    n_pdm_mac_flag VARCHAR(1),
    n_min_reimb_amt NUMERIC(18, 2),
    n_electronic_fee NUMERIC(18, 2),
    n_incentive_fee NUMERIC(18, 2),
    n_disc_net_fee NUMERIC(18, 2),
    n_mac_awp_prcnt NUMERIC(18, 4),
    n_mac_awp_num INTEGER,
    n_awp_litigation_factor NUMERIC(18, 4),
    n_mac_factor_table INTEGER,
    n_340b_cap NUMERIC(18, 2),
    n_eft_fee NUMERIC(18, 2),
    n_wac_fee NUMERIC(18, 2),
    n_wac_prcnt NUMERIC(18, 4),
    n_340b_disp_fee NUMERIC(18, 2),
    n_reimb_fixed_amt NUMERIC(18, 2),
    n_reimb_cap_amt NUMERIC(18, 2),
    n_add_id VARCHAR(15),
    n_change_id VARCHAR(15),
    n_add_date TIMESTAMP,
    n_chg_date TIMESTAMP,
    y_gen_code CHAR(6),
    y_reim_desc_type FLOAT8,
    y_awp_pcnt NUMERIC(18, 4),
    y_disp_fee NUMERIC(18, 2),
    y_mac_tbl INTEGER,
    y_mac_fee NUMERIC(18, 2),
    y_flat_fee NUMERIC(18, 2),
    y_cap_amt NUMERIC(18, 2),
    y_per_month VARCHAR(1),
    y_active VARCHAR(1),
    y_otc_fee NUMERIC(18, 2),
    y_pay_as_contract_rate VARCHAR(1),
    y_marketing_percentage NUMERIC(18, 4),
    y_marketing_disp_fee NUMERIC(18, 2),
    y_plus_diff_table_1 INTEGER,
    y_plus_diff_table_eff_1 TIMESTAMP,
    y_plus_diff_table_2 INTEGER,
    y_plus_diff_table_eff_2 TIMESTAMP,
    y_plus_diff_table_3 INTEGER,
    y_plus_diff_table_eff_3 TIMESTAMP,
    y_pdm_mac_flag VARCHAR(1),
    y_min_reimb_amt NUMERIC(18, 2),
    y_electronic_fee NUMERIC(18, 2),
    y_incentive_fee NUMERIC(18, 2),
    y_disc_net_fee NUMERIC(18, 2),
    y_mac_awp_prcnt NUMERIC(18, 4),
    y_mac_awp_num INTEGER,
    y_awp_litigation_factor NUMERIC(18, 4),
    y_mac_factor_table INTEGER,
    y_340b_cap NUMERIC(18, 2),
    y_eft_fee NUMERIC(18, 2),
    y_wac_fee NUMERIC(18, 2),
    y_wac_prcnt NUMERIC(18, 4),
    y_340b_disp_fee NUMERIC(18, 2),
    y_reimb_fixed_amt NUMERIC(18, 2),
    y_reimb_cap_amt NUMERIC(18, 2),
    y_add_id VARCHAR(15),
    y_change_id VARCHAR(15),
    y_add_date TIMESTAMP,
    y_chg_date TIMESTAMP,
    o_add_on_percent NUMERIC(18, 4),
    m_add_on_percent NUMERIC(18, 4),
    n_add_on_percent NUMERIC(18, 4),
    y_add_on_percent NUMERIC(18, 4)
);
