-- =============================================
-- Table: cloud_data_warehouse.scriptcaresnapshot
-- Columns: 55
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.scriptcaresnapshot (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_src_sys_nm VARCHAR(80),
    meta_iud_flg VARCHAR(1),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    claim_key VARCHAR(14),
    batch_number VARCHAR(8),
    claim_number INTEGER,
    claim_type VARCHAR(1),
    bin_number INTEGER,
    software_cert_id_sub VARCHAR(10),
    ing_cost_sub NUMERIC(18, 2),
    disp_fee_sub NUMERIC(18, 2),
    flat_sales_tax_amt_sub NUMERIC(18, 2),
    percent_sales_tax_amt_sub NUMERIC(18, 2),
    incentive_amt_sub NUMERIC(18, 2),
    other_amt_claimed_sub NUMERIC(18, 2),
    gross_amt_due_sub NUMERIC(18, 2),
    usual_custom_charge_i_sub NUMERIC(18, 2),
    patient_paid_amt_sub NUMERIC(18, 2),
    basis_cost_determination_sub VARCHAR(2),
    employer_id_sub VARCHAR(15),
    cmpd_ingr_drug_cost_sub NUMERIC(18, 2),
    ingredient_cost_paid_resp NUMERIC(18, 2),
    disp_fee_paid_resp NUMERIC(18, 2),
    flat_sales_tax_amt_paid_resp NUMERIC(18, 2),
    percent_sales_tax_amt_paid_resp NUMERIC(18, 2),
    incentive_amt_paid_resp NUMERIC(18, 2),
    other_amt_claimed_paid_resp NUMERIC(18, 2),
    total_amt_paid_resp NUMERIC(18, 2),
    usual_custom_charge_or_esp NUMERIC(18, 2),
    est_generic_savings_resp NUMERIC(18, 2),
    basis_reimb_determination_resp INTEGER,
    prior_auth_nbr_assign_resp BIGINT,
    ing_cost_billed NUMERIC(18, 2),
    ing_cost_paid NUMERIC(18, 2),
    disp_fee NUMERIC(18, 2),
    tax NUMERIC(18, 2),
    calc_amt NUMERIC(18, 2),
    ucr_amt NUMERIC(18, 2),
    basis_cost_determ VARCHAR(2),
    mac_refer_price NUMERIC(18, 2),
    contract_rate NUMERIC(18, 2),
    awp_100_perc NUMERIC(18, 2),
    price_ind VARCHAR(1),
    rej_code_1 INTEGER,
    rej_code_2 INTEGER,
    except_code_1 INTEGER,
    except_code_2 INTEGER,
    mac_number INTEGER,
    trans_date DATE,
    network_pricing_applies VARCHAR(1),
    add_date DATE
);
