-- =============================================
-- Table: cloud_data_warehouse.state_compliance
-- Columns: 60
-- Schema Source: Enterprise Data Warehouse Data Schema.csv
-- =============================================

CREATE TABLE cloud_data_warehouse.state_compliance (
    meta_surr_key VARCHAR(1000),
    meta_hash_key VARCHAR(1000),
    meta_src_sys_nm VARCHAR(80),
    meta_iud_flg VARCHAR(1),
    meta_eff_strt_dt TIMESTAMP,
    meta_eff_end_dt TIMESTAMP,
    meta_curr_ind VARCHAR(3),
    state_id VARCHAR(2) NOT NULL,
    rec_type VARCHAR(3) NOT NULL,
    date_type VARCHAR(2) NOT NULL,
    data_type VARCHAR(3) NOT NULL,
    data VARCHAR(14) NOT NULL,
    occ INTEGER NOT NULL,
    seq_nbr INTEGER NOT NULL,
    eff_date TIMESTAMP,
    term_date TIMESTAMP,
    lob_1 VARCHAR(10),
    lob_2 VARCHAR(10),
    lob_3 VARCHAR(10),
    lob_4 VARCHAR(10),
    lob_5 VARCHAR(10),
    lob_6 VARCHAR(10),
    lob_7 VARCHAR(10),
    lob_8 VARCHAR(10),
    lob_9 VARCHAR(10),
    lob_10 VARCHAR(10),
    lob_11 VARCHAR(10),
    lob_12 VARCHAR(10),
    lob_13 VARCHAR(10),
    lob_14 VARCHAR(10),
    lob_15 VARCHAR(10),
    lob_16 VARCHAR(10),
    lob_17 VARCHAR(10),
    lob_18 VARCHAR(10),
    lob_19 VARCHAR(10),
    lob_20 VARCHAR(10),
    lob_21 VARCHAR(10),
    lob_22 VARCHAR(10),
    lob_23 VARCHAR(10),
    lob_24 VARCHAR(10),
    lob_25 VARCHAR(10),
    trans_fee_001 NUMERIC(18, 2),
    price_source_002 VARCHAR(10),
    low_val_disp_002 NUMERIC(18, 2),
    price_source_disp_002 NUMERIC(18, 2),
    percent_002 NUMERIC(18, 4),
    days_supply_elec_003 INTEGER,
    days_supply_paper_003 INTEGER,
    copay_cap_30_day_004 NUMERIC(18, 2),
    copay_cap_90_day_004 NUMERIC(18, 2),
    copay_type_code_004 INTEGER,
    tax_percent_005 NUMERIC(18, 4),
    flat_tax_005 NUMERIC(18, 2),
    rebate_amt_006 NUMERIC(18, 2),
    rebate_type_006 VARCHAR(5),
    add_id VARCHAR(15),
    change_id VARCHAR(15),
    add_date TIMESTAMP,
    change_date TIMESTAMP,
    cap_90_app_flag_004 VARCHAR(1)
);
