#!/bin/sh
#
# Description: Move all converted files into production 

SHELL_DIR=/usr/lnk/shell
RPT_DIR=/usr/lnk/rpt
GRP_DIR=/usr/lnk/grp
RCP_DIR=/usr/lnk/crd_01
ETRAF_DIR=/usr/lnk/claims
NSD_DIR=/usr/lnk/drug

# GROUP00MAS file
chmod 666 ${GRP_DIR}/GROUP00MAS-NEW; chgrp pdm ${GRP_DIR}/GROUP00MAS-NEW
mv ${GRP_DIR}/GROUP00MAS ${GRP_DIR}/GROUP00MAS-OLD
mv ${GRP_DIR}/GROUP00MAS-NEW ${GRP_DIR}/GROUP00MAS

# PLAN000MAS file
chmod 666 ${GRP_DIR}/PLAN000MAS-NEW; chgrp pdm ${GRP_DIR}/PLAN000MAS-NEW
mv ${GRP_DIR}/PLAN000MAS ${GRP_DIR}/PLAN000MAS-OLD
mv ${GRP_DIR}/PLAN000MAS-NEW ${GRP_DIR}/PLAN000MAS

# BENEF00MAS file
chmod 666 ${GRP_DIR}/BENEF00MAS-NEW; chgrp pdm ${GRP_DIR}/BENEF00MAS-NEW
mv ${GRP_DIR}/BENEF00MAS ${GRP_DIR}/BENEF00MAS-OLD
mv ${GRP_DIR}/BENEF00MAS-NEW ${GRP_DIR}/BENEF00MAS

# CONFIG0MAS file
chmod 666 ${GRP_DIR}/CONFIG0MAS-NEW; chgrp pdm ${GRP_DIR}/CONFIG0MAS-NEW
mv ${GRP_DIR}/CONFIG0MAS ${GRP_DIR}/CONFIG0MAS-OLD
mv ${GRP_DIR}/CONFIG0MAS-NEW ${GRP_DIR}/CONFIG0MAS

# RCP0000MAS file
chmod 666 ${RCP_DIR}/RCP0000MAS-NEW; chgrp pdm ${RCP_DIR}/RCP0000MAS-NEW
mv ${RCP_DIR}/RCP0000MAS ${RCP_DIR}/RCP0000MAS-OLD
mv ${RCP_DIR}/RCP0000MAS-NEW ${RCP_DIR}/RCP0000MAS

# ETRAF00MAS file
chmod 666 ${ETRAF_DIR}/ETRAF00MAS-NEW
mv ${ETRAF_DIR}/ETRAF00MAS ${ETRAF_DIR}/ETRAF00MAS-OLD
mv ${ETRAF_DIR}/ETRAF00MAS-NEW ${ETRAF_DIR}/ETRAF00MAS

# NSDEOVRMAS file
chmod 666 ${NSD_DIR}/NSDEOVRMAS-NEW; chgrp pdm ${NSD_DIR}/NSDEOVRMAS-NEW
mv ${NSD_DIR}/NSDEOVRMAS ${NSD_DIR}/NSDEOVRMAS-OLD
mv ${NSD_DIR}/NSDEOVRMAS-NEW ${NSD_DIR}/NSDEOVRMAS

exit 0
